### PR TITLE
React 17

### PR DESCRIPTION
**Pull request by kyledurand**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-react/issues/4271

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, ping @ sarahill to update the Polaris UI kit

### CODE REVIEW

**Comment by paulisloud** [comment]
Is there any update on when this should be finalized?

**Comment by kyledurand** [comment]
We're still hoping for this week. We're in the process of removing all references to `test-utilities/legacy` which means fully migrating our tests `@shopify/react-testing`. Then we can remove enzyme and support both react 16 and 17

**Comment by kyledurand** [comment]
Small update: We just shipped the [last PR](https://github.com/Shopify/polaris-react/pull/4456) to remove the legacy test helpers. I've updated this PR to remove enzyme and a few things we no longer need. 

I don't know what `environtments.ts` does off the top of my head but it's still referencing enzyme. Hopefully we can sort that out on Tuesday and cut a release

**Review by alex-page — APPROVED** [review]

**Review by BPScott — APPROVED** [review]
Hecks yea, looking great!

There's a few console errors in the test output but I think they were there before too.

**Comment by paulisloud** [comment]
Nice to see this merged. Any idea when it will be in a release published to npm?

**Pull request merged**
