### PR TITLE
[Banner] Fixes unexpected text wrap in Firefox on focus of secondary action button

### PR DESCRIPTION
**Pull request by afairbrother**
### WHY are these changes introduced?

Fixes unexpected text-wrap when focusing the `secondaryAction` in Firefox (referenced here: https://github.com/Shopify/polaris-react/pull/4997#pullrequestreview-869952961) 

### WHAT is this pull request doing?

Before: 

https://user-images.githubusercontent.com/10119562/152183009-4d860f52-8d73-4dbf-9c93-7f668b7cfd6a.mp4

After: 

https://user-images.githubusercontent.com/10119562/152183329-e1f151d5-2a31-4e73-b1cf-689d0a705867.mov

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';

import {Page, Banner} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
      <Banner
        title="Some of your product variants are missing weights"
        status="warning"
        action={{content: 'Edit variant weights', url: ''}}
        secondaryAction={{content: 'Learn more', url: ''}}
        onDismiss={() => {}}
      >
        <p>
          Add weights to show accurate rates at checkout and when buying shipping
          labels in Shopify.
        </p>
      </Banner>
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, ping @ sarahill to update the Polaris UI kit

### CODE REVIEW

**Review by dleroux — COMMENTED** [review]
:shipit:

**Review by dleroux — APPROVED** [review]

**Review by lgriffee — APPROVED** [review]
🚢✨🎉🔥 Thanks so much @afairbrother!

**Review by chloerice — APPROVED** [review]
Thanks again @afairbrother and nice catch @lgriffee!! 🚀

**Comment by afairbrother** [comment]
Updated, and moved `display: block` to only be on focus. Thoughts on this, @dleroux ? 

Before: 
image

After: 
Screen Shot 2022-02-02 at 14 54 45

**Review by dleroux — APPROVED** [review]

**Pull request merged**
