### PR TITLE
Update drag handle icon

### PR DESCRIPTION
**Pull request by isabelxklee**
### WHAT is this pull request doing?
Updating the drag handle icon, per [Issue #1137](https://github.com/Shopify/polaris/issues/11372).

Comparison:
difference

Before:
before

After:
after

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by alex-page** [comment]
@zecarlostorre @isabelxklee @heyjoethomas I recently updated this icon in this commit. Is this still needed?

See this commit: https://github.com/Shopify/polaris/pull/11138/commits/f31e4979c7d1399e655883a9594a74f18799e4cb

**Comment by isabelxklee** [comment]
@alex-page oh darn, it looks like this work was duplicated due to multiple issues detailing the same work. i'll close this issue + PR. thanks!

**Comment by alex-page** [comment]
Sorry about that. Thanks a ton for the contribution. If you want to add yourself as an author we should still do that.

**Comment by isabelxklee** [comment]
@alex-page aw thank you so much! sure, that would be great.

**Pull request closed without merging**
