### PR TITLE
memoize buildCustomProperties function

### PR DESCRIPTION
**Pull request by tmlayton**
### WHY are these changes introduced?

This function takes somewhere between 5 and 10ms on a fast machine in a sandbox, multiply that by many theme providers, slow machines, and production environments and times go up significantly. 

### WHAT is this pull request doing?

Memoizing `buildCustomProperties`

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}

```

</details>

### 🎩 checklist

* [x] 🎩

### CODE REVIEW

**Comment by BPScott** [comment]
How does this work with server-side rendering where the server is a long running process? Will the map keep getting larger over time without ever freeing up any memory?

[The one place buildCustomProperties is used](https://github.com/Shopify/polaris-react/blob/master/src/components/ThemeProvider/ThemeProvider.tsx#L60-L64) is is already wrapped in a `useMemo` (which does handle occasionally throwing out old value to release memory pressure) so it doesn't seem like this adds much value.


https://github.com/Shopify/polaris-react/pull/3527 demonstrates that the useMemo around is buildCustomProperties is always cachebusted because because the memo wrapped around processedThemeConfig is messed up. By fixing the dependencies of the call to useMemo in ThemeProvider as detailed in that PR we sidestep needing to add this 4th! set of memoisation.

**Comment by dfmcphee** [comment]
> [The one place buildCustomProperties is used](https://github.com/Shopify/polaris-react/blob/master/src/components/ThemeProvider/ThemeProvider.tsx#L60-L64) is is already wrapped in a `useMemo` (which does handle occasionally throwing out old values to release memory pressure) so it doesn't seem like this adds much value.

The difference is that `useMemo` will only memoize it for that component instance, and since we have ThemeProviders all over the page, they won't share that cached value unless we move that up to a higher level component. Really we only want to ever run that function for the default values once for the default light and dark theme configs (we don't even use the customization right now). This could even be in a build process as it should never change dynamically.

**Comment by BPScott** [comment]
Does useMemo still act that way if you extract the call into a hook (which is then used by multiple instances of a single component)?

I was wondering about that last night: 

> TODO: Once we fix this we should investigate if the useMemo cache is shared between multiple instances of a ThemeProvider so that we can utilize even more caching. this might involve abstracting the "working out all the theme stuff" out into a hook. (I thinks this might mean that the cache can be shared between multiple renderings of ThemeProvider if it isn't already)

**Review by alex-page — APPROVED** [review]

**Comment by tmlayton** [comment]
> How does this work with server-side rendering where the server is a long running process? Will the map keep getting larger over time without ever freeing up any memory?

No, it won’t grow to more than a handful of values so should be fine.

> Does useMemo still act that way if you extract the call into a hook (which is then used by multiple instances of a single component)?

I don't know—if it does I'm in favor of that approach and we can use this until then.

**Comment by BPScott** [comment]
Had a play with "will hooks let us share between component instances" and the answer is no: https://codesandbox.io/s/youthful-andras-3ltyt?file=/src/App.js. It still ends up memoizing once per component instance rather than sharing between items (if it shared between component instances I'd expect calledHook to only be triggered once).

All very good. Ignore me :)

**Comment by tmlayton** [comment]
Thanks for looking into it @BPScott! I certainly would have preferred if we could have done this the React way.

**Pull request merged**
