### PR TITLE
[polaris.shopify.com] Fixed capitalization of CodeSandbox in link

### PR DESCRIPTION
**Pull request by adam-ruf-shopify-ux**
BEFORE
'Edit in Codesandbox'
image

AFTER
'Edit in CodeSandbox'
image

### CODE REVIEW

**Comment by ghost** [comment]
👋 Thanks for opening your first pull request. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by adam-ruf-shopify-ux** [comment]
👋 New Shopifolk (2nd week of onboarding) here with my first PR.
I wasn't expecting any failing tests with simple text change, did I miss something required for passing the **Changelog / check (pull_request)** check?

**Comment by martenbjork** [comment]
Hi Adam! Welcome to Shopify! 🔥 

You just need to generate a "changeset" to make this PR pass. https://github.com/Shopify/polaris/pull/6581/files

Let me know if you need any help!

**Comment by adam-ruf-shopify-ux** [comment]
Hi @martenbjork, thanks for the warm welcome and info!

Because I'm not a developer and not familiar with changeset, I would love some help, so I can keep focused on onboarding and my other priorities.

When you have a moment, will you please help me generate the changeset to pass the test and get this PR merged in? 🙏

**Review by martenbjork — APPROVED** [review]

**Comment by martenbjork** [comment]
@adam-ruf-shopify-ux I went ahead and added the changeset so you can keep focusing on higher priority stuff for your onboarding 😊 Hit me up down the road if you need help contributing with Polaris and we can set up some time to jam! 🚀

**Pull request merged**
