### PR TITLE
Update browser config

### PR DESCRIPTION
**Pull request by AndrewMusgrave**
### WHY are these changes introduced?

Update to the shared browser config

### CODE REVIEW

**Comment by BPScott** [comment]
Nice!

We shouldn't need to specify `@shopify/browserslist-config` directly in package.json as it's already a transitive dependency of sewing-kit (and this config like eslint config / stylelint config is the one case that we do want to rely on the transitive dependency instead of being explicit)

**Comment by BPScott** [comment]
Oh I've just pushed a commit to the v5 branch that [fixes up that package.json/yarn.lock noise](https://github.com/Shopify/polaris-react/commit/d51727b6cbf9a795e64a8578c9fdc0c544c32a57) rebase and you can get rid of those changes.

**Comment by BPScott** [comment]
Took the liberty of acting upon the changes requested so I can get this merged. Thanks!

**Comment by AndrewMusgrave** [comment]
@BPScott Thanks 🙇

**Pull request merged**
