### PR TITLE
[WIP][Frame] Remove left property from Navigation class

### PR DESCRIPTION
**Pull request by kyledurand**
### WHY are these changes introduced?

Fixes: https://github.com/Shopify/destinations/issues/664

### WHAT is this pull request doing?

I'm changing the `transform: translateX(60px)` in global-nav: https://github.com/Shopify/global-nav/pull/149 to a padding-left. Removing `left: 0` here means the nav will respect that padding. I've tophatted this change in chrome, safari, firefox and chromium edge 👍. Aside from the global nav not rendering at all in chromium edge this doesn't seem to break things

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}

```

</details>

### 🎩 checklist

* [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Comment by kyledurand** [comment]
I wonder where that percy conflict is coming from because there's no visual change in my local shop. Wondering if that's part of the story board setup that adds a padding of 8px to the frame cc @BPScott would you happen to know?

**Comment by BPScott** [comment]
> Wondering if that's part of the story board setup that adds a padding of 8px to the frame cc @BPScott would you happen to know?

That seems likely to me. Perhaps we should let stories configure if they want that padding or not in the same way as how they can choose to render with an AppProvider wrapping them or not. (Search for omitAppProvider and bother Tim for more info on that)

**Comment by dfmcphee** [comment]
I am seeing a slight offset for the mobile nav without the `left: 0`. Is this the storybook padding you were mentioning or is this a different issue?

Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-01 at 09 26 59

**Comment by kyledurand** [comment]
Confirmed @dfmcphee 

image

You can remove the padding from adjusting this line: https://github.com/Shopify/polaris-react/blob/master/.storybook/preview.js#L22

There should be a way to remove this padding for full screen stories. I'll look into it

**Comment by kyledurand** [comment]
Closing this in favour of https://github.com/Shopify/polaris-react/pull/2887

**Pull request closed without merging**
