### PR TITLE
[ResourceList] Fix Item click deselect

### PR DESCRIPTION
**Pull request by ruairiphackett**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-react/issues/1882

This PR addresses an issue where the `ResourceList` `Item`s (with selection) would retain a focused state when deselected by clicking on the `Item` itself in the `ResourceList` ([video of issue](https://screenshot.click/24-22-iv47s-hvvll.mp4)).

### WHAT is this pull request doing?

The `ResourceList` `Item` component's `handleSelection` handler is called whenever an `Item` is selected. This includes clicking on the `Item` when it is already selected using the checkbox.

This PR changes the logic from `handleSelection` always setting the `focused` and `focusedInner` values in state to true, to setting them to `!selected` which means that they are set to false when the `Item` is deselected by clicking on it.

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import * as React from 'react';
import {Avatar, Card, ResourceList, TextStyle} from '../src';

interface State {}

export default class Playground extends React.Component<{}, State> {
  state = {
    selectedItems: [],
  };

  handleSelectionChange = (selectedItems) => {
    this.setState({selectedItems});
  };

  renderItem = (item) => {
    const {id, url, name, location} = item;
    const media = <Avatar customer size="medium" name={name} />;

    return (
      <ResourceList.Item
        id={id}
        url={url}
        media={media}
        accessibilityLabel={`View details for ${name}`}
      >
        <h3>
          <TextStyle variation="strong">{name}</TextStyle>
        </h3>
        <div>{location}</div>
      </ResourceList.Item>
    );
  };

  render() {
    const resourceName = {
      singular: 'customer',
      plural: 'customers',
    };

    const items = [
      {
        id: 341,
        url: 'customers/341',
        name: 'Mae Jemison',
        location: 'Decatur, USA',
      },
      {
        id: 256,
        url: 'customers/256',
        name: 'Ellen Ochoa',
        location: 'Los Angeles, USA',
      },
    ];

    return (
      <Card>
        <ResourceList
          resourceName={resourceName}
          items={items}
          renderItem={this.renderItem}
          selectedItems={this.state.selectedItems}
          onSelectionChange={this.handleSelectionChange}
          selectable
        />
      </Card>
    );
  }
}
```

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by danrosenthal** [comment]
Hey @ruairiphackett, thanks for the contribution, and sorry for the delay on getting feedback and review. Would you be willing to add a regression test for this change? An appropriate test would select the item, then click it, and assert that the handler was not called.

**Comment by ruairiphackett** [comment]
Thanks for taking a look @danrosenthal! I'll add that test and fix the conflict as soon as I get a chance.

**Comment by ruairiphackett** [comment]
@danrosenthal Looking at what you suggested for the test, I think I may have approached this incorrectly. I changed the behaviour so that if an item is clicked after it has been selected, it will be unselected (as shown [in this video](https://screenshot.click/30-04-x8xkd-rg212.mp4)).

Is this approach incorrect? Should the `onClick` callback be called even if the clicked item has already been selected?

**Comment by danrosenthal** [comment]
Sorry @ruairiphackett, it seems I misread the original problem. Please disregard what I said

**Pull request merged**
