### PR TITLE
[polaris.shopify.com] Update table styles

### PR DESCRIPTION
**Pull request by sarahill**
Update table styling to match designs in Figma

| Before | After |
|---|---|
| Screen Shot 2022-07-14 at 8 36 26 AM | Screen Shot 2022-07-14 at 8 36 42 AM |
| image | Screen Shot 2022-07-14 at 8 22 38 AM |

Tested in:
- Chrome
- Safari

### CODE REVIEW

**Review by alex-page — APPROVED** [review]
Thank you @sarahill

**Comment by martenbjork** [comment]
Beautiful!

**Comment by zecarlostorre** [comment]
@sarahill, for the table, does this include the padding increment we looked at? Or did you give up on that?

**Comment by sarahill** [comment]
@zecarlostorre That'll be a separate PR :) I created a new branch when we were working on those. I'll tag you for review just need to clean it up and will do that shortly

**Pull request merged**
