### PR TITLE
Fixes Badge when it becomes 2 lines due to small viewport.

### PR DESCRIPTION
**Pull request by tarynmusgrave**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-react/issues/899 

We are using Polaris-next for Badges in web currently to include this change. To prevent issues/updates with the new design language we would love to get this (or similar) added to Polaris. 

### WHAT is this pull request doing?

BEFORE 
Deformed Badge component

AFTER
single line Badge component in small viewport

multi line Badge component in small viewport

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';

import {Page, Badge} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      <Badge progress="incomplete" status="attention">
        Unfulfilled
      </Badge>
      <Badge progress="partiallyComplete" status="warning">
        Partially fulfilled
      </Badge>
    </Page>
  );
}

```

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [X] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [X] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [X] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Comment by tarynmusgrave** [comment]
Looking for comments before updating changelog & percy.

**Review by ry5n — APPROVED** [review]
Even though it’s good to avoid situations where badges get squished like this, this is clearly a better outcome if it does in fact happen. 👍  from me. Might be good to get another set of eyes on this, maybe @alex-page?

**Review by alex-page — APPROVED** [review]
Looks good, I do agree with @ry5n though. This should be avoided or maybe made impossible by the component 🤔

**Comment by tarynmusgrave** [comment]
Yup, need to do the changelog and the percy changes but other than that if you are both happy I will get it out there and then remove all of the polaris-next badges.

**Comment by alex-page** [comment]
🚢

**Pull request merged**
