### PR TITLE
[color-transformers > rgbToHsbl] Fix brightness precision of HSB conversions by increasing from 2 decimal digits to 4

### PR DESCRIPTION
**Pull request by MLDimitry**
### WHY are these changes introduced?

I was originally investigating this issue in Shopify web https://github.com/Shopify/shopify/issues/265949

and found that the color-transformers on Polaris would convert both hex values `#888888` and `#878787` to the same HSB value `{ hue: 0, saturation: 0, brightness: 0.53 }`. The calculating actually looked correct, `#888888` was being converted to `0.5333` and `#878787` was being converted to `0.5294`. But the final step of the conversion limits these to only two decimal places, which resulted in the brightness values being rounded to `0.53` in both cases and losing their precision.

The Shopify Web ticket has more details on the original issue.

### WHAT is this pull request doing?

This PR fixes the `color-transformers` issue by increasing the brightness value's precision from 2 decimal points to 4. 

It also adds two tests for the failing conversions from the Shopify web issue for `rgb(135, 135, 135)` and `rgb(136, 136, 136)` to ensure they're both translated to the correct expected values.

# Questions for reviewers

* Is this change a bug fix? Or would we consider changing the number of decimal digits as a breaking change?
* Thoughts on updating Polaris version in Shopify web? Should we create a workaround/short term fix in Shopify web for now instead of updating Polaris during the holiday critical phase?

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers) **_(Firefox and Chrome)_**
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] ~Updated the component's `README.md` with documentation changes~ **_(Didn't see any README for utilities)_**
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by alex-page — APPROVED** [review]

**Review by kyledurand — APPROVED** [review]
👍

**Comment by MLDimitry** [comment]
@alex-page @kyledurand Any thoughts on these two questions before I merge:

* Is this change a bug fix? Or would we consider changing the number of decimal digits as a breaking change? Our type hasn't changed so I lean towards bug fix, since consumers shouldn't rely on `toFixed(2)` implementation details
* Since Polaris UNRELEASED.md contains more than just bug fixes, I don't think we want to update the version in Shopify/web directly, would you agree? Or should I work to cut a new release?

**Comment by kyledurand** [comment]
> Is this change a bug fix? Or would we consider changing the number of decimal digits as a breaking change?

Could be considered a bug fix but I can't see it as a breaking change. If you need this available in web right away then we could cut a release with just this commit in it.

**Comment by MLDimitry** [comment]
> If you need this available in web right away then we could cut a release with just this commit in it.

Yes I think that would be best, then I can tophat the fix on web staging before bumping there.

I'm going to kick off the merge this morning. If you guys can help me cut the release once it's merged, or point me to some docs on the process so I can release it myself, that'd be great.

**Pull request merged**
