### PR TITLE
[Tabs] Add Action Element to Tab Header

### LINKED ISSUE #995: [Tabs] Support actions in Tab panel
# Feature request summary
Tabs should support actions to enable more flexible layout.

## Rationale
This feature will allow actions to exit on the right of tabs.
```
--------------------------
Container
[Tabs]              [Reload]
--------------------------
[Tab content]
--------------------------
```
52427419-dc0ccf00-2acd-11e9-90b6-1d65df4a9707

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

### PR DESCRIPTION
**Pull request by elizabethletourneau**
### WHY are these changes introduced?

Before there was no way to include an action into the Tabs header. This PR adds a action prop to the Tabs Header section.

Fixes #995  

### WHAT is this pull request doing?
Adds an IconableAction prop to the `Tabs` component. Some updates were done to the `TabMeasurer` component and the `getVisibleAndHiddenTabIndices` utility to handle different states of the size of the action Tab and the disclosure activator tab.

 Before:

After: 
action takes either an Icon or content (with or without a URL for each) 
If an Icon is present, content will not show. 

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import * as React from 'react';
import {CancelSmallMinor} from '@shopify/polaris-icons';
import {Page, Card, Tabs, Icon} from '../src';

interface State {}

export default class Playground extends React.Component<{}, State> {
  state = {
    selected: 0,
  };

  handleTabChange = (selectedTabIndex) => {
    this.setState({selected: selectedTabIndex});
  };

  render() {
    const {selected} = this.state;
    const tabs = [
      {
        id: 'all-customers',
        content: 'Pineapple',
        accessibilityLabel: 'All customers',
        panelID: 'all-customers-content',
      },
      {
        id: 'accepts-marketing',
        content: 'Accepts marketing',
        panelID: 'accepts-marketing-content',
      },
      {
        id: 'repeat-customers',
        content: 'Repeat customers',
        panelID: 'repeat-customers-content',
      },
      {
        id: 'prospects',
        content: 'Prospects',
        panelID: 'prospects-content',
      },
    ];

    const makeMeADisclusoreTabs = [
      {
        id: 'all-customers',
        content: 'Pineapple',
        accessibilityLabel: 'All customers',
        panelID: 'all-customers-content',
      },
      {
        id: 'accepts-marketing',
        content: 'Accepts marketing',
        panelID: 'accepts-marketing-content',
      },
      {
        id: 'repeat-customers',
        content: 'Repeat customers',
        panelID: 'repeat-customers-content',
      },
      {
        id: 'prospects',
        content: 'Prospects',
        panelID: 'prospects-content',
      },
      {
        id: 'notProspects',
        content: 'Not Prospects',
        panelID: 'notprospects-content',
      },
      {
        id: 'maybeProspects',
        content: 'Maybe Prospects',
        panelID: 'maybeprospects-content',
      },
    ];

    return (
      <Page title="Playground">
        <p> With Icon fitted</p>
        <Card>
          <Tabs
            tabs={tabs}
            selected={selected}
            onSelect={this.handleTabChange}
            fitted
            action={{
              disabled: true,
              icon: <Icon source={CancelSmallMinor} />,
              external: true,
              url: 'https://facebook.com',
              content: 'GoToThere',
            }}
          >
            <Card.Section title={tabs[selected].content}>
              <p>Tab {selected} selected</p>
            </Card.Section>
          </Tabs>
        </Card>
        <p> With Content fitted</p>
        <Card>
          <Tabs
            tabs={tabs}
            selected={selected}
            onSelect={this.handleTabChange}
            fitted
            action={{
              external: true,
              url: 'https://facebook.com',
              content: 'GoToThere',
            }}
          >
            <Card.Section title={tabs[selected].content}>
              <p>Tab {selected} selected</p>
            </Card.Section>
          </Tabs>
        </Card>
        <p> With Icon Regular</p>
        <Card>
          <Tabs
            tabs={tabs}
            selected={selected}
            onSelect={this.handleTabChange}
            action={{
              icon: <Icon source={CancelSmallMinor} />,
              external: true,
              url: 'https://facebook.com',
              content: 'GoToThere',
            }}
          >
            <Card.Section title={tabs[selected].content}>
              <p>Tab {selected} selected</p>
            </Card.Section>
          </Tabs>
        </Card>
        <p> With Content Regular</p>
        <Card>
          <Tabs
            tabs={tabs}
            selected={selected}
            onSelect={this.handleTabChange}
            action={{
              external: true,
              url: 'https://facebook.com',
              content: 'GoToThere',
            }}
          >
            <Card.Section title={tabs[selected].content}>
              <p>Tab {selected} selected</p>
            </Card.Section>
          </Tabs>
        </Card>
        <p> With Icon regular</p>
        <Card>
          <Tabs
            tabs={tabs}
            selected={selected}
            onSelect={this.handleTabChange}
            action={{
              icon: <Icon source={CancelSmallMinor} />,
              external: true,
              url: 'https://facebook.com',
              content: 'GoToThere',
            }}
          >
            <Card.Section title={tabs[selected].content}>
              <p>Tab {selected} selected</p>
            </Card.Section>
          </Tabs>
        </Card>

        <p> With Icon regular and Disclosure</p>
        <Card>
          <Tabs
            tabs={makeMeADisclusoreTabs}
            selected={selected}
            onSelect={this.handleTabChange}
            action={{
              icon: <Icon source={CancelSmallMinor} />,
              external: true,
              url: 'https://facebook.com',
              content: 'GoToThere',
            }}
          >
            <Card.Section title={tabs[selected].content}>
              <p>Tab {selected} selected</p>
            </Card.Section>
          </Tabs>
        </Card>
        <p> With Content regular and Disclosure</p>
        <Card>
          <Tabs
            tabs={makeMeADisclusoreTabs}
            selected={selected}
            onSelect={this.handleTabChange}
            action={{
              external: true,
              url: 'https://facebook.com',
              content: 'GoToThere',
            }}
          >
            <Card.Section title={tabs[selected].content}>
              <p>Tab {selected} selected</p>
            </Card.Section>
          </Tabs>
        </Card>
      </Page>
    );
  }
}


```

</details>

### 🎩 checklist

* [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [x] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)

### CODE REVIEW

**Comment by elizabethletourneau** [comment]
@mirualves I've changed the colours of the content of the link over to blue :) please let me know what you think. I was thinking it could also be a matter of adding a separator and distinguishes the actions from the tabs. like a | .

**Comment by mirualves** [comment]
> @mirualves I've changed the colours of the content of the link over to blue :) please let me know what you think. I was thinking it could also be a matter of adding a separator and distinguishes the actions from the tabs. like a | .

Excellent! The blue on the link looks better and it's consistent with our guidelines. I kind of like the idea of using a separator, but I'm not sure if it'll make the region looks too busy. @ry5n, do you think it would be valid to add a separator between the `Tabs` and `Link`?

**Comment by ry5n** [comment]
In discussing the original issue, there were a couple of directions mentioned (there might be more):

1. Add a dedicated prop for placing elements to the right of the tabs
2. Expose the tab strip and tab content panel as separate components, like how we give you the option of using Card.Header manually if you need more control over that part of a Card. You could import the tab strip and content panel, place them within any desired layout, and then wire them together manually (insert hand waving here).

I want to make sure these (and maybe other options) were considered—there are pros and cons to each. Can you outline the rationale for going with option 1?

**Comment by mirualves** [comment]
If I understood everything correctly, I believe the option 1 and 2 are not mutually exclusive (option 2 might actually give more flexibility overall by splitting the component, I think it's worth exploring), and option 2 wouldn't address the original issue of including an action into the Tabs header.

Maybe I'm missing some context in how option 2 would solve the issue.

**Comment by AndrewMusgrave** [comment]
@mirualves The second approach would allow the consumer to position the two components however they please and use the section for anything, which includes actions 😄

**Comment by elizabethletourneau** [comment]
@ry5n  @mirualves Option two was not explored because Option one seemed like a good MVP to start with and solved the initial issue however seeing the action prop with only content (and no icon) does raise the issue that the action is a bit indistinguishable from the other tabs (especially on fitted mode). Before developing option two would it be possible to hash out a design concept of where the actions would be laid out and what the differences between a Tabs.Header component and the existing Tabs component would be? 🦑 🌈 🐎

**Comment by ry5n** [comment]
Update from last week. @AndrewMusgrave and @elizabethletourneau chatted last week, and were able to weight the options mentioned in the original issue.

Although it’s faster and easier to add an action prop to tabs to support a button on the right of the tab strip, this might not scale. We know of at least one scenario on an existing product that isn’t accounted for by the action prop.

We got a better idea of how the alternative approach would work, and decided that this would be more flexible, and probably not that much harder to engineer.

We’re going to switch gears and try this second approach.

**Comment by chloerice** [comment]
I’m going to close this, as it looks like the last decision made in this discussion was to go with a different approach (a flexible Header subcomponent)

**Comment by furnaceX** [comment]
Is there a solution for this you could link us to?

**Pull request closed without merging**
