### PR TITLE
[Filters] Removed id from proxy buttons

### PR DESCRIPTION
**Pull request by AndrewMusgrave**
### WHY are these changes introduced?

* Fixes internally linked issue (see below)
* Fixes accessibility failures in https://github.com/Shopify/polaris-react/pull/3646

### WHAT is this pull request doing?

Remove id's from proxy buttons (button that are being used to measure)

### How to 🎩

* Load a filters example
* Check if the id's are removed from the proxy markup

### CODE REVIEW

**Comment by BPScott** [comment]
Yay A11y issue fixing up!

CI is failing because it expects you to remove no-longer occurring errors from the expected errors list.

https://travis-ci.com/github/Shopify/polaris-react/jobs/443941780#L893 details what is removed
https://github.com/Shopify/polaris-react/blob/master/scripts/accessibility-check.js#L88 is array you need to remove items from

**Comment by AndrewMusgrave** [comment]
Can't say I've ever had a code fail before it was too accessible 😛

**Comment by BPScott** [comment]
I think I prefer the approach in #3653 where "proxy" is passed in a second option object instead of being jammed into the action object.

**Review by kyledurand — APPROVED** [review]
I did my [PR](https://github.com/Shopify/polaris-react/pull/3653) pretty quickly and haven't updated tests or anything yet. Happy to let you ship this, with Bens comment addressed, and rebase mine after. Planning to tackle the rest of these next week.

**Review by ashwinnarayanan2001 — APPROVED** [review]

**Comment by AndrewMusgrave** [comment]
Thanks, @kyledurand @BPScott 🙌

**Pull request merged**
