### PR TITLE
update app provider and theme provider readme to discourage production use

### PR DESCRIPTION
**Pull request by danrosenthal**
|Theme provider|App provider|
|-|-|
|screencapture-polaris-myshopify-io-components-structure-theme-provider-2020-03-09-10_19_48|screencapture-polaris-myshopify-io-components-structure-app-provider-2020-03-09-10_19_22|

### CODE REVIEW

**Comment by danrosenthal** [comment]
More close up screenshots

|Theme provider|App provider|
|-|-|
|Screen Shot 2020-03-09 at 10 23 48 AM|Screen Shot 2020-03-09 at 10 23 39 AM|

**Comment by elizabethmcguane** [comment]
@danrosenthal On the Theme Provider page, could we place the 'For development purposes only' text at the start of the 'Example' section — even just a short note, with the more complete text below — to make the two pages consistent in how they display this warning?

**Comment by danrosenthal** [comment]
All set @elizabethmcguane:

|Edited|
|-|
|screencapture-polaris-myshopify-io-components-structure-theme-provider-2020-03-09-11_27_43|

**Comment by elizabethmcguane** [comment]
LGTM!

**Pull request merged**
