### PR TITLE
[Dropzone] Removed reference to window

### PR DESCRIPTION
**Pull request by AndrewMusgrave**
### WHY are these changes introduced?

Removing all reference to `window` on code that can execute on the client

### CODE REVIEW

**Comment by BPScott** [comment]
Could you say why this is needed? I'm at a complete loss why this might be needed - I'd love to learn what weird case I'm overlooking.

**Comment by dleroux** [comment]
To be honest we are unsure. We had to roll back 4.9 from web this morning because of bugsnag error claiming window was undefined.

Do you know how we could test this with SSR before shipping?

**Comment by AndrewMusgrave** [comment]
> Could you say why this is needed? I'm at a complete loss why this might be needed - I'd love to learn what weird case I'm overlooking.

Was going to ask Dan to paste in the bugsnag link cc/ @dleroux 

We're referencing window on the client `useEventListener(window` which doesn't fly in ssr land. This change will make it easier attaching event listeners to the window in the future

**Comment by dleroux** [comment]
```
node_modules/@shopify/polaris/esnext/components/DropZone/DropZone.js:139
window is not defined
```

**Comment by BPScott** [comment]
Had a chat wilth @dleroux: This is weird, I'm not a  fan and I wonder if using isServer we can avoid adding options to uesEventListener. That said this is internal stuff and we can come back to it later, finding a cleaner solution shouldn't block release of this.

**Pull request merged**
