### PR TITLE
[ComboBox]: prevent component props mutation.

### LINKED ISSUE #2764: Displaying Incorrect Suggested Tags in Multiple tag autocomplete
## Issue summary
Displaying incorrect Suggested Tags while typing in text field

https://codesandbox.io/s/priceless-bouman-plndu?fontsize=14&hidenavigation=1&theme=dark

## Expected behavior
Displaying string match Suggested Tags
image

## Actual behavior
Displaying unrelated tag
image

## Steps to reproduce the problem

1. this may be re-produceable when the element is loaded first time.  Multiple try may not show the symptom.  (reload or reload frame when it is necessary)
1. start type "e" then "f"

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.13.1
- Browser: Chrome Version 80.0.3987.87
- Device: 
- Operating System: mac OS Mojave version 10.14.6

```bash

```

### PR DESCRIPTION
**Pull request by alllx**
### WHY are these changes introduced?
Because of unexpected search options result was displayed like unexpected options result or duplicated options (see animation below).

Fixes #2764 

### WHAT is this pull request doing?
Prevents passed component props mutation.

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}

```

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Comment by dleroux** [comment]
How were you able to tophat your `actionsBefore` and `actionsAfter` changes?

`actionsBefore` throws an error: Maximum update depth exceeded, and I'm seeing `actionsAfter`. If you got this to work can you provide a playground?

**Comment by BPScott** [comment]
I'm not familiar with AutoComplete, so I'm probably not the best person to review this, looks like @dleroux has got your back though

**Comment by alllx** [comment]
> How were you able to tophat your `actionsBefore` and `actionsAfter` changes?
> 
> `actionsBefore` throws an error: Maximum update depth exceeded, and I'm seeing `actionsAfter`. If you got this to work can you provide a playground?

Let me double check this in Playground, there is a test which is passed: `src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx:191`

**Comment by alllx** [comment]
> I'm not familiar with AutoComplete, so I'm probably not the best person to review this, looks like @dleroux has got your back though

Hey @dleroux checked `actionBefor` on master same error so I didn't introduce this error. This issue should be tackled in the separate PR.
Here is my Playground.tsx code please check it in storybook on master.
```tsx
import React from 'react';
import {CirclePlusMinor} from '@shopify/polaris-icons';

import {Page, Autocomplete} from '../src';

export function Playground() {
  const textField = (
    <Autocomplete.TextField
      onChange={(value) => console.log(value)}
      label=""
      value=""
      placeholder="placeholder"
    />
  );
  return (
    <Page title="Playground">
      <Autocomplete
        options={[
          {
            label: 'label 1',
            value: '1',
          },
          {
            label: 'label 2',
            value: '2',
          },
        ]}
        selected={['1']}
        onSelect={() => console.log('update')}
        textField={textField}
        actionBefore={{
          content: "Add 'f'",
          icon: CirclePlusMinor,
          id: 'ComboBox3-0',
        }}
      />
    </Page>
  );
}
```

**Comment by dleroux** [comment]
The code looks good, but mine keeps crashing, even with your playground on master. I've reopened the [issue](https://github.com/Shopify/polaris-react/issues/989#issuecomment-598277628) that was closed. Hopefully someone has time to tackle it soon but that's another issue.

**Pull request merged**
