### PR TITLE
[Navigation] - Fix active page highlighted state

### PR DESCRIPTION
**Pull request by yourpalsonja**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-ux/issues/18

### WHAT is this pull request doing?

Updates the active state for navigation items, making it a11y friendly. 
before
after

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

You can click on "Orders" to expand it and see a `selected` sub-nav item.

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import * as React from 'react';
import {Page} from '@shopify/polaris';

interface State {}

export default class Playground extends React.Component<never, State> {
  render() {
    return (
      <Page title="Playground">
       <Navigation location="/">
          <Navigation.Section
            items={[
              {
                url: '/path/to/place',
                label: 'Home',
                icon: 'home',
              },
              {
                url: '/path/to/place',
                label: 'Orders',
                icon: 'orders',
                badge: '15',
                subNavigationItems: [
                  {
                    url: '/path/to/place',
                    label: 'Closed',
                    selected: true,
                  },
                  {
                    url: '/path/to/place',
                    label: 'Open',
                  },
                ],
              },
              {
                url: '/path/to/place',
                label: 'Products',
                icon: 'products',
                selected: true,
              },
            ]}
          />
        </Navigation>
      </Page>
    );
  }
}
```

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)

### CODE REVIEW

**Comment by yourpalsonja** [comment]
@dpersing We've updated most of the glaring issues, and have decided to hold on making sure the hover state colouring is accessible until after the new brand roll-out. We're looking to make sure the `Selected` state is accessible. I'll attach a gif below.

**Comment by yourpalsonja** [comment]
interaction-states
Here are the different mocked-up interaction states. I know it's unrealistic to have two `Selected` items, this is just for illustrative purposes to show what primary and secondary `NavigationItem`s will look like.

cc @jessebc @ry5n wanted you to take another look at these!

**Comment by jessebc** [comment]
Is it the active state that has the border on the left-hand side? That jumped out to me as feeling a bit unexpected.

**Comment by ry5n** [comment]
The bar is for focus. Ideally it should only appear when navigating via the keyboard. I thought we’d suppressed it at least when clicking the links with the mouse. @yourpalsonja do you know where we netted out on that? (We could leave focus changes to a follow-up PR)

**Comment by yourpalsonja** [comment]
@ry5n @jessebc 

Right now, it appears as a style for:
- keyboard `focus` and `active` events
- mouse `focus` events

Do we not want it to appear for mouse interactions at all?

**Comment by ry5n** [comment]
> Do we not want it to appear for mouse interactions at all?

I think so. Ideally, the focus ring should be hidden for links/buttons when interacting via the mouse. Related to https://github.com/Shopify/polaris-ux/issues/132

**Comment by ry5n** [comment]
I don’t want to let this stall. If we have concerns about focus or hover style changes, let’s revert them and do them in a follow-up. We will need to update the Sketch UI kit though when this goes in.

**Comment by danrosenthal** [comment]
What's the status on this PR @yourpalsonja?

**Comment by yourpalsonja** [comment]
@danrosenthal @ry5n just waiting for another +1 after the changes!

**Comment by ry5n** [comment]
🎉 YAS

**Pull request merged**
