### PR TITLE
Fix `@shopify/polaris-tokens` treeshaking

### PR DESCRIPTION
**Pull request by aaronccasanova**
### WHAT is this pull request doing?

This PR adds `"sideEffect": "false"` to the `@shopify/polaris-tokens` `package.json` to enable treeshaking.

### How to 🎩

- Create a new project

```sh
mkdir my-project && cd my-project
```

- Initialize a `package.json` and install the test dependencies

```
npm init -y && npm install vite @shopify/polaris-tokens@0.0.0-snapshot-20240406000953
```

- Create a basic `vite.config.js` file using library mode

```js
import * as vite from 'vite'

export default vite.defineConfig({
  build: {
    minify: false,
    lib: {
      entry: 'index.js',
      name: 'MyLib',
      fileName: 'my-lib',
    },
  },
})
```

- Create an `index.js` file with a single named import from `@shopify/polaris-tokens`

```js
import { themes } from '@shopify/polaris-tokens'

console.log('themes:', themes)
```

- Run a production build

```sh
npx vite build
```

**Before**
image

**After**
image

### CODE REVIEW

**Review by alex-page — APPROVED** [review]

**Review by sam-b-rose — APPROVED** [review]

**Comment by sam-b-rose** [comment]
@aaronccasanova anything blocking here? If not, I think it is ready to be merged.

**Comment by juzser** [comment]
Thanks for updating!

**Comment by juzser** [comment]
Thanks for the update @aaronccasanova !

**Pull request merged**
