### PR TITLE
🔥 add base tsconfig

### PR DESCRIPTION
**Pull request by michelleyschen**
### WHY are these changes introduced?

We now have [base typescript configurations](https://github.com/Shopify/sewing-kit/tree/master/packages/typescript-configs) that project can pull in.
I am using polaris here as a test for library project. 

Note that `@shopify/typescript-configs` actually come with the latest sewing-kit. 
However I am too afraid to update sewing-kit myself so I pull in `@shopify/typescript-configs` separately instead.

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

As long as type-check passed we are all good!

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import * as React from 'react';
import {Page} from '@shopify/polaris';

interface State {}

export default class Playground extends React.Component<never, State> {
  render() {
    return (
      <Page title="Playground">
        {/* Add the code you want to test here */}
      </Page>
    );
  }
}
```

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by BPScott** [comment]
Reminding myself to look at this when you're ready

**Comment by BPScott** [comment]
> However I am too afraid to update sewing-kit myself so I pull in @shopify/typescript-configs separately instead.

We use SK for our testing and linting scaffolding, we don't use it for builds so it's a pretty low impact change. I'll try and spin up a new PR to update to latest SK (to check theres no unrelated changes), then we can rebase this change atop that once it's merged. How does that sound?

**Comment by michelleyschen** [comment]
Rebased with the master!

**Comment by AndrewMusgrave** [comment]
Late to the party but LGTM ✅ 🎉

**Pull request merged**
