### PR TITLE
[DualThumb] Add an offset to push the minimum range value to the left

### PR DESCRIPTION
**Pull request by mathildebuenerd**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-react/issues/4155

When using the [Dual thumb range slider](https://polaris.shopify.com/components/forms/range-slider) with a min value different from 0, there is an extra padding on the left. This prevents selecting a value when having a range [10, 50] for example:

Screenshot 2021-05-06 at 11 10 43

Screenshot 2021-05-06 at 11 09 26

| What's happening | What's expected |
|--|--|
| current | expected

### WHAT is this pull request doing?

Substract the minimum range value position to the position.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';

import {Page} from '../src';
import {DualThumb} from '../src/components/RangeSlider/components/DualThumb';

export function Playground() {
  const handleChange = (value) => value;
  return (
    <Page title="Playground">
      <DualThumb
        id="test"
        label="Range=[0,50] - Value=[10,50]"
        min={0}
        max={50}
        value={[10, 50]}
        step={1}
        onChange={handleChange}
      />
      <DualThumb
        id="test"
        label="Range=[10,50] - Value=[10,50]"
        min={10}
        max={50}
        value={[10, 50]}
        step={1}
        onChange={handleChange}
      />
      <DualThumb
        id="test"
        label="Range=[10,50] - Value=[20,40]"
        min={10}
        max={50}
        value={[20, 40]}
        step={1}
        onChange={handleChange}
      />
     <DualThumb
        id="test"
        label="Range=[-10,30] - Value=[-10,-9]"
        min={-10}
        max={30}
        value={[-10, -9]}
        step={1}
        onChange={handleChange}
      />
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Review by mathildebuenerd — COMMENTED** [review]
Not sure if I should add an entry to the changelog?

**Review by LauraAubin — APPROVED** [review]
Tophat is working as expected!

I think you want to add a changelog entry under bug fixes

**Comment by mathildebuenerd** [comment]
@LauraAubin cool thank you, I added it to unreleased.md

**Comment by mathildebuenerd** [comment]
@tmlayton good point! here it is: https://github.com/Shopify/polaris-react/pull/4172/files#diff-fb6dd9f5964ac9e139777a5b04ccfc26a3a9572afc221dc55a04ea840d2906aeR300-R333

**Pull request merged**
