### PR TITLE
prepare 3.7.0 release

### PR DESCRIPTION
**Pull request by danrosenthal**

### CODE REVIEW

**Comment by danrosenthal** [comment]
- **styleguide PR:** https://github.com/Shopify/polaris-styleguide/pull/2552
- **web PR:** [tk]

**Comment by danrosenthal** [comment]
@BPScott I'm noticing in my [:tophat: on React views in `web`](https://github.com/Shopify/web/pull/10577) that icons are not appearing.

|icons 🤷‍♂️|
|-|
|screen shot 2019-02-11 at 10 00 59 am|

Could this be to do with https://github.com/Shopify/polaris-react/commit/8e369561409706a5f0dbc6f43780b512820c518f?

**Comment by amrocha** [comment]
Possibly, but Percy found no issues for Ben's PR so I'm thinking it's something deeper than that. Unfortunately the way the Icon component works makes it very hard to debug issues like this sometimes. Are there any errors in the console?

**Comment by danrosenthal** [comment]
@amrocha after recloning web, I am now able to see all the icons in my tophat.

|:tophat:|
|-|
|screen shot 2019-02-11 at 3 24 39 pm|

Going to blame this one on caching and move ahead with the release

**Comment by danrosenthal** [comment]
@BPScott or @tmlayton would one of you give me an approval on this so I can go ahead and release `3.7.0`?

**Comment by tmlayton** [comment]
👍 FWIW

**Pull request merged**
