### PR TITLE
[Tabs] Fix aria-require-* issues & listitem semantic issue

### PR DESCRIPTION
**Pull request by jaxee**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/web/issues/34726 - aria-require-child / parent rule
Fixes https://github.com/Shopify/web/issues/34493 - list elements not being used semantically
Fixes https://github.com/Shopify/web/issues/34925 - screen reader tab amount (ex. 1 of 7)

### WHAT is this pull request doing?

No visual changes to the component.
Added `role='presentation'` to the list elements within the unordered list. This removes semantic meaning from the list element which solves three issues;
- li elements not being used semantically
- aria-require-child/parent rule
- screen reader tab amount (before: tab 1 of 1, after: tab 1 of 7)

***Voice over***
The screen reader now reads `Tab x of x`:
voiceover

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, { useCallback, useState } from "react";

import {Page, Tabs, Card} from '../src';

export function Playground() {
  const [selected, setSelected] = useState(0);

  const handleTabChange = useCallback(
    (selectedTabIndex) => setSelected(selectedTabIndex),
    []
  );

  const tabs = [
    {
      id: "all-customers",
      content: "All",
      accessibilityLabel: "All customers",
      panelID: "all-customers-content"
    },
    {
      id: "accepts-marketing",
      content: "Accepts marketing",
      panelID: "accepts-marketing-content"
    },
    {
      id: "repeat-customers",
      content: "Repeat customers",
      panelID: "repeat-customers-content"
    },
    {
      id: "prospects",
      content: "Prospects",
      panelID: "prospects-content"
    },
    {
      id: "prospects2",
      content: "Prospects",
      panelID: "prospects-content2"
    },
    {
      id: "prospects3",
      content: "Prospects",
      panelID: "prospects-content3"
    },
    {
      id: "prospects4",
      content: "Prospects",
      panelID: "prospects-content4"
    }
  ];

  return (
    <Page title="Playground">
      
      <Card>
        <Tabs tabs={tabs} selected={selected} onSelect={handleTabChange}>
          <Card.Section title={tabs[selected].content}>
            <p>Tab {selected} selected</p>
          </Card.Section>
        </Tabs>
      </Card>
    </Page>
  );
}
```
</details>

Copy and paste the above code into your local `Playground.tsx` file. Run your server.
- Test that you can still navigate the tabs correctly with your keyboard
- Test the screen reader, the expected behaviour is that the screen reader will say `Tab 1 of x` instead of `Tab 1 of 1`
- Run the `Accessibility Insights` Chrome extension, ensure the aria-require-* rule does not come up as well as the listitem semantic rule

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers) (Tested on Chrome, FireFox and Safari)
* [x] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [x] Updated the component's `README.md` with documentation changes
* [x] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [x] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Review by AndrewMusgrave — APPROVED** [review]
Nice work! This will close a few issues 😍

**Comment by BPScott** [comment]
In #3653 @kyledurand changed these roles to be `tab` instead of `presentation`. I assume because they're rendered inside a   ul with the role `tablist`. What's the better approach?

**Comment by BPScott** [comment]
Kinda bamboozled about why no CI has ran for this PR :/ We should make sure that works before merging this, as I expect this will remove a bunch of expected a11y errors

**Comment by jaxee** [comment]
@BPScott I explained why I think this approach is better in [this thread](https://github.com/Shopify/polaris-react/pull/3653#discussion_r530544424)

I will go fix the merge conflicts and hopefully that will force CI to run properly?

**Comment by AndrewMusgrave** [comment]
> Kinda bamboozled about why no CI has ran for this PR :/ We should make sure that works before merging this, as I expect this will remove a bunch of expected a11y errors

It's quite a few checks that haven't run so I'm guessing it was a github issue. Hopefully, it was a one time issue and pushing again will let them work as expected 🤞

**Comment by BPScott** [comment]
Eeey CI is running!

It is failing because a handful of expected a11y test failures are no longer occurring 🎉 : https://travis-ci.com/github/Shopify/polaris-react/jobs/448195889#L893

You'll need to remove the mentioned lines from this array: https://github.com/Shopify/polaris-react/blob/master/scripts/accessibility-check.js#L88

(We fail when these errors no longer occur, so we know we have to remove them from the list. This avoids a situation where we make a fix, don't remove the "ignore this error" line, and then reintroduce the issue again at a later date)

**Review by BPScott — APPROVED** [review]
Nice one! Thanks for digging into this and putting up with my questions!

Looks like we're doing what the [MDN examples](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role) offer, as per https://github.com/Shopify/polaris-react/pull/3653#discussion_r530544424
 the `role=tab` is applied to the button/link directly inside this li that we're giving the role of presentation

**Comment by ginabak** [comment]
This PR also: 

Fixes https://github.com/Shopify/polaris-react/issues/3657 and https://github.com/Shopify/polaris-react/issues/2442 🥳

**Pull request merged**
