### PR TITLE
[ContextualSaveBar][PageActions] Updated `primaryAction` button to `primary`

### PR DESCRIPTION
**Pull request by yurm04**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-summer-editions/issues/932

### WHAT is this pull request doing?

With uplift enabled in storybook

`ContextualSaveBar`
Screenshot 2023-07-13 at 6 28 54 PM

`PageActions`
Screenshot 2023-07-13 at 6 28 28 PM

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by sarahill — APPROVED** [review]

**Review by aveline — CHANGES_REQUESTED** [review]
Sorry this is so confusing, but you don't need to add the beta flag in. A straight switch back to `primary` is all that is needed since `primary` and `primarySuccess` render the same with the beta flag turned off.

Seems like it's a matter of undoing [the changes in this PR](https://github.com/Shopify/polaris/pull/9503/files).

**Review by sam-b-rose — APPROVED** [review]

**Review by aveline — APPROVED** [review]

**Review by chloerice — COMMENTED** [review]
@sarahill @yurm04 These actions being primary instead of primary success was flagged a couple weeks ago and fixed because the Save actions are primarySuccess at the Page level, so for PageActions and ContextualSaveBar equivalents not to match looked off. cc @zecarlostorre

**Comment by sarahill** [comment]
@chloerice This issue was based off a convo from last week. The consensus was to update both `Page` `secondaryActions` and `PageActions` to use `primary` instead of `primarySuccess`. More context [here](https://github.com/Shopify/polaris-summer-editions/issues/916#issuecomment-1634295588)

**Comment by yurm04** [comment]
@chloerice @sarahill just confirming we're good to merge this into the system based on @sarahill's comment above?

**Comment by sarahill** [comment]
@yurm04 Yep! confirmed with José this is the intended state. 🚢

**Comment by zecarlostorre** [comment]
@chloerice @sarahill - I created the issue to update all save buttons to green, but last week there was a discussion thread that resulted in us moving away from the green buttons across the board.
I [closed the issue](https://github.com/Shopify/polaris-summer-editions/issues/916#issuecomment-1634295588) with a screenshot from the thread for context.

**Comment by chloerice** [comment]
Thanks for the context y'all!! 🚀

**Pull request merged**
