### PR TITLE
[Tag] Clarify that onClick and onRemove are mutually exclusive

### PR DESCRIPTION
**Pull request by chloerice**
### WHY are these changes introduced?

 #2986  brought to my attention that there isn't a removable tag example, and that it needs to be documented that clickable tags aren't removable.

### WHAT is this pull request doing?

This PR adds a removable tag example and clarifies that the remove button doesn't render when `onClick` is set. 

***Note: The pa11y test failure is due to [a bug reported with `Autocomplete`](https://github.com/Shopify/polaris-react/issues/3639).

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [x] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Comment by danrosenthal** [comment]
Would it be important to actually remove the tag in the example?

**Comment by chloerice** [comment]
> Would it be important to actually remove the tag in the example?

It's moreso illustrating that setting `onRemove` adds a remove button you can wire up. But we do have a simple tag example in the `Autocomplete` docs I can copy over!

**Comment by BPScott** [comment]
Could we also help enforce this in the Typescript declaration of Tag's props? TextField does similar where [you can have only one of `readonly`, `disabled` or `onChange`)[https://github.com/Shopify/polaris-react/blob/master/src/components/TextField/TextField.tsx#L117]

**Comment by chloerice** [comment]
> Could we also help enforce this in the Typescript declaration of Tag's props? TextField does similar where [you can have only one of `readonly`, `disabled` or `onChange`](https://github.com/Shopify/polaris-react/blob/master/src/components/TextField/TextField.tsx#L117)

Marc [did that](https://github.com/Shopify/polaris-react/blob/24d63e3e9d50cb0fe3c72889e64c8227a980da87/src/components/Tag/Tag.tsx#L23) for `Tag` as well.

**Comment by BPScott** [comment]
Cool, ignore me :)

**Comment by BPScott** [comment]
It feels a little odd for the demo of removable tag to not show any on initial render, but to instead show an autocomplete box.Doesn't fee very useful for our VRT stuff.

How about something like this as an example:

```js
function RemovableTagExample() {
  const [selectedTags, setSelectedTags] = useState([
    'Rustic',
    'Antique',
    'Vinyl',
    'Refurbished',
  ]);

  const removeTag = useCallback(
    (tag) => () => {
      setSelectedTags((previousTags) =>
        previousTags.filter((previousTag) => previousTag !== tag),
      );
    },
    [],
  );

  const tagMarkup = selectedTags.map((option) => (
    <Tag key={option} onRemove={removeTag(option)}>
      {option}
    </Tag>
  ));

  return <Stack spacing="tight">{tagMarkup}</Stack>;
}
```

**Review by kyledurand — APPROVED** [review]
Code looks good to me 🥇 Thank Chloe!

**Comment by chloerice** [comment]
@kyledurand Would you mind merging this for me? I don't have admin privileges and the pa11y failures don't have anything to do with this PR (the autocomplete is setting `aria-expanded` on the text field instead of the combobox wrapper, see https://github.com/Shopify/polaris-react/issues/3639).

**Comment by kyledurand** [comment]
I can merge for you but I'd prefer if you could add those two failing ids to our accessibility checks list https://github.com/Shopify/polaris-react/blob/master/scripts/accessibility-check.js#L88

**Comment by BPScott** [comment]
No need to fixup a11y tests skip lists if we've already fixed all our failing a11y tests :thonk:

**Pull request merged**
