### PR TITLE
[Navigation] Fix sub nav item spacing when no icon is present

### PR DESCRIPTION
**Pull request by kyledurand**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/global-nav/issues/706

image

### How to 🎩

Comment out the icons on the details page

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Review by alex-page — APPROVED** [review]
That was straight forward! Thanks @kyledurand

**Comment by alex-page** [comment]
If it is easy we should try to get the text to line up.
Screen Shot 2020-10-27 at 9 40 11 PM

**Comment by kyledurand** [comment]
Good call! Slightly tighter spacing does the trick

image

**Comment by alex-page** [comment]
Amazing! Ship it

**Pull request merged**
