### PR TITLE
Add generic migration to update component props

### PR DESCRIPTION
**Pull request by aaronccasanova**
This PR introduces a generic migration for updating React component props. Features include:
- Prop renames
- Prop value updates:
  * `string` to `string`
  * `boolean` to `string`
- Handles deeply nested compound components
- Inserts Polaris migrator comments on known edge cases (e.g. components with a spread operator)

Examples:

- Prop rename:

```sh
npx @shopify/polaris-migrator react-update-component-prop \
  --componentName Component \
  --fromProp prop \
  --toProp newProp \
  <glob>

# <Component prop="value" /> -> <Component newProp="value" />
```

- Prop value update (`string` to `string`):

```sh
npx @shopify/polaris-migrator react-update-component-prop \
  --componentName Component \
  --fromProp prop \
  --toValue new-value \
  <glob>

# <Component prop="value" /> -> <Component prop="new-value" />
```

- Prop value update (`boolean` to `string`):

```sh
npx @shopify/polaris-migrator react-update-component-prop \
  --componentName Component \
  --fromPropType boolean \
  --fromProp prop \
  --toProp newProp \
  --toValue new-value \
  <glob>

# <Component prop /> -> <Component newProp="new-value" />
```

- Prop specific value update:

```sh
npx @shopify/polaris-migrator react-update-component-prop \
  --componentName Component \
  --fromProp prop \
  --fromValue value \
  --toValue new-value \
  <glob>

# <Component prop="value" /> -> <Component prop="new-value" />
# <Component prop="foo" /> -> <Component prop="foo" />
```

- Prop rename and value update:

```sh
npx @shopify/polaris-migrator react-update-component-prop \
  --componentName Component \
  --fromProp prop \
  --toProp newProp \
  --fromValue value \
  --toValue new-value \
  <glob>

# <Component prop="value" /> -> <Component newProp="new-value" />
# <Component prop="foo" /> -> <Component prop="foo" />
```

- Prop rename (nested compound component):

```sh
npx @shopify/polaris-migrator react-update-component-prop \
  --componentName Component.Nested.CompoundComponent \
  --fromProp prop \
  --toProp newProp \
  <glob>

# <Component.Nested.CompoundComponent prop="value" /> -> <Component.Nested.CompoundComponent newProp="value" />
```

### CODE REVIEW

**Comment by kyledurand** [comment]
I've been noticing some [issues with generic migrations as well](https://github.com/Shopify/polaris/issues/10909) and was about to start looking into them. Let me know if you want to jam on this

**Review by chloerice — APPROVED** [review]
Test cases look solid 💯 :shipit:

**Review by sophschneider — APPROVED** [review]

**Pull request merged**
