### PR TITLE
[Button] Add expanded styling

### PR DESCRIPTION
**Pull request by kyledurand**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-internal/issues/1073

### WHAT is this pull request doing?

Adds some styling to show when a button is in an `aria-expanded` state. This is most noticeable on popovers / collapsible elements where the button is controlling the expanded state of another element

This does not add the styling to anything other than the default button and page secondary actions. i.e. Primary, Critical, Primary success are not affected since they shouldn't be used to control other expanded elements

### How to 🎩

A few places to look

https://admin.web.popovers.kyle-durand.us.spin.dev/store/shop1/dashboards
https://admin.web.popovers.kyle-durand.us.spin.dev/store/shop1
https://admin.web.popovers.kyle-durand.us.spin.dev/store/shop1/products?selectedView=all

https://5d559397bae39100201eedc1-ywdplrxrms.chromatic.com/?path=/story/all-components-popover--all

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by zecarlostorre — COMMENTED** [review]
I noticed a few things:

In cards, the active state doesn't match the active state of the button
Screenshot 2023-11-14 at 19 01 39

- In small cards, there's even a padding issue happening
Screenshot 2023-11-14 at 19 01 15

And then there's this expand/collapse button that seems to be affected, when it shouldn't.

**Review by laurkim — APPROVED** [review]
Spin and code changes lgtm 💯 🚀

**Review by zecarlostorre — APPROVED** [review]

**Pull request merged**
