### PR TITLE
Revert "Fix several cyclical type imports"

### PR DESCRIPTION
**Pull request by kvendrik**
### Description
Reverts Shopify/polaris-react#691 as it breaks color exports.

### How to 🎩 
1. On this branch:`yarn build-consumer web`.
2. In Web: `yarn run type-check`.
3. Make sure you get no more errors related to missing color types and helpers.

### CODE REVIEW

**Comment by amrocha** [comment]
Oh, actually, running `yarn run type-check` is giving me an error but I'm not sure if it's related to this.

```
➜  web git:(master) yarn run type-check
yarn run v1.10.1
$ sewing-kit type-check
[graphql] Built GraphQL schema types
[error] Cannot query field "publication" on type "ResourcePublication"
error Command failed with exit code 1.
```

It might be because my local web setup is bad?

**Comment by kvendrik** [comment]
> Oh, actually, running yarn run type-check is giving me an error but I'm not sure if it's related to this.

Don't think that's related. Make sure your `shopify/shopify` is on the latest master.

**Comment by amrocha** [comment]
I haven't run `shopify/shopify` in months lmao

**Comment by amrocha** [comment]
Alright my local web setup is not gonna get fixed anytime soon so if you ran this locally and it worked then I trust your judgement on this

**Comment by BPScott** [comment]
#691 contained two commits, one for color utility stuff and one for a selection of other type tweaks. If it's just the color exports causing a problem can we reinstate the other commit?

**Comment by amrocha** [comment]
Ben you're on vacation, don't worry about it we got it go back to skiing

**Comment by kvendrik** [comment]
@BPScott I'll leave that decision to @amrocha and @tmlayton. 🙂

**Pull request merged**
