### PR TITLE
[ToastManager] Change aria-live to assertive for accessibility

### PR DESCRIPTION
**Pull request by tarynmusgrave**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/web/issues/34584 

Toast messages using aria-live set to 'polite' are ignored by screen reader. There is discussion in the linked PR as for the decision made to choose this solution over extending the time a toast spends on screen. 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [X] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Review by kyledurand — COMMENTED** [review]
Wondering if we could default to assertive and add a prop that allows consumers to change to polite?

cc @alex-page and @kaelig do you think `assertive` might be too much for all popovers? Just thinking out loud 🤷‍♂️

**Comment by kaelig** [comment]
Thanks for the ping! I'd recommend going for assertive as suggested in this pull request, and adding a prop only if we receive feedback that this creates issues in specific instances.

**Comment by AndrewMusgrave** [comment]
I have the same thoughts as @kaelig . API is easy to add but difficult to remove. Since we think this is the best, accessible choice let's roll with it and extend the API based on feedback.

**Review by AndrewMusgrave — COMMENTED** [review]
LGTM ✅ I'll 🎩 web in the morning

**Review by kaelig — APPROVED** [review]
I haven't had the chance to tophat but it makes sense. This may be something we consider as a "bug fix" rather than an announcement, but that's a nit pick!

**Review by AndrewMusgrave — APPROVED** [review]
🎩 💯

**Pull request merged**
