### PR TITLE
Make `utilities/focus` helpers available to consumers

### LINKED ISSUE #3738: Make helpers from `src/utilities/focus.ts` available to consumers
## Feature request summary

Make helpers from `src/utilities/focus.ts` available to consumers.

## Rationale

There are a lot of helpful helpers in `src/utilities/focus.ts`. They could definitely benefit other Shopify projects. :)

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

### PR DESCRIPTION
**Pull request by ben10code**
### WHY are these changes introduced?

Fixes #3738 

This PR makes the helpers in `utilities/focus.ts` publicly available to consumers. 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Comment by BPScott** [comment]
I'm generally a bit wary of exposing our utilities. it means that if we ever change our internals we're stuck with having to support a bunch of functions that we no longer use.

Many of these were copied from https://github.com/shopify/javascript-utilities. If you find them useful then you should either use that package or add these bits of functionality into a project in quilt or copy what you need into your own app.

**Comment by tleunen** [comment]
I wasn't aware some of these focus utils were available in the [shared JS libs](https://github.com/Shopify/javascript-utilities/blob/master/src/focus.ts). I think it would indeed make more sense for a consumer app to import them from `@shopify/javascript-utilities` than from `polaris`.
@ben10code - If some functions are missing from the js utilities, feel free to add them there instead.

> Many of these were copied from https://github.com/shopify/javascript-utilities. If you find them useful then you should either use that package or add these bits of functionality into a project in quilt or copy what you need into your own app.

Any reason why Polaris wouldn't use the shared shopify utils instead of copying them? Is it to keep Polaris as "self-sufficient" as much as possible?

**Comment by BPScott** [comment]
> Any reason why Polaris wouldn't use the shared shopify utils instead of copying them? Is it to keep Polaris "self-sufficient" as much as possible?

Per the comment at the top of its readme `@shopify/javascript-utilities` is deprecated. It also only exports commonJS content which means we don't treeshake away any unused utility functions. As part of v5 I removed our dependency on `@shopify/javascript-utilities` and chose to inline the functions we needed as it turned out we had a bunch of focus management helpers already and creating an extra package in quilt didn't seem worth the overhead. 

See https://github.com/Shopify/polaris-react/pull/3102 and https://github.com/Shopify/polaris-react/pull/3108 for some of those changes.

**Comment by BPScott** [comment]
A small further clarification on:

> I'm generally a bit wary of exposing our utilities. it means that if we ever change our internals we're stuck with having to support a bunch of functions that we no longer use.

I see `@shopify/polaris` as a component library first and foremost. We're shouldn't be responsible for maintaining low-level helpers - that's what the packages in Quilt are for.

**Comment by tleunen** [comment]
Makes sense! Thanks @BPScott

**Comment by ben10code** [comment]
Thanks for the insight Ben! Closing this PR and issue :)

**Pull request closed without merging**
