### PR TITLE
[Docs][Patterns] Fix `dl` styling in `DefinitionTable`

### LINKED ISSUE #10369: Patterns `Use when` section has weird spacing
Match the spacing that's on prod. Component usage can be found in pattern variant pages `/content/patterns/**/*.md`

Image

### PR DESCRIPTION
**Pull request by laurkim**
### WHY are these changes introduced?

Fixes #10369.

### WHAT is this pull request doing?

Fixes selector for `dl` styling inside `DefinitionTable` class for patterns pages.
    <details>
      <summary>Before</summary>
      Before
    </details>
    <details>
      <summary>After</summary>
      After
    </details>

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by sam-b-rose — APPROVED** [review]
Curious why this class selector specificity was too low for this element?? Could we remove the `dl` styling that is conflicting with this set of rules so we don't have to change the specificity? This is the only non-class selector in this file–the inconsistency seems odd

**Review by yurm04 — COMMENTED** [review]
I think this change is better to make in the `PatternPage` where we pass in the mdx components to the `Markdown` renderer. You can see an example of this [here](https://github.com/Shopify/polaris/blob/889bdab4b8aaa3519c26684eb1f4cbb5c4e10bbe/polaris.shopify.com/src/components/PatternPage/PatternPage.tsx#L320) where we're already passing in the `DefinitionList` component. You can also override normal html elements like `dl` and replace them with whatever JSX you want. Here's what I recommend

```
dl: ({children}) => (
    <Box as="dl" className={styles.DefinitionList}>
      {children}
    </Box>
  ),
```

now any `dl` in the pattern page will get the `DefinitionList` css module styling. This would address the specificity concerns and make it consistent with the rest of the file

**Comment by laurkim** [comment]
> Curious why this class selector specificity was too low for this element?? 

@sam-b-rose looks like we previously added the `DefinitionList` class to `dl` elements in the markdown but it was removed in the `next` branch, so the styles from the class were never being applied. Going to follow @yurm04's suggestion and update the PatternsPage mdx components instead and revert updates to `PatternPage.modules.scss`.

> Could we remove the dl styling that is conflicting with this set of rules so we don't have to change the specificity? This is the only non-class selector in this file–the inconsistency seems odd

Do you mean in the `PatternPage.modules.scss` file? There are other instances of a class selector with children element selectors (i.e., [UnorderedList](https://github.com/Shopify/polaris/blob/4e884eed7feb572e7cf004612ad6fd962037a8bf/polaris.shopify.com/src/components/PatternPage/PatternPage.module.scss#L246)) so it wouldn't be inconsistent with other ways we use non-class selectors in this file but I'm not sure if the file you're referring to is the PatternsPage one

**Comment by sam-b-rose** [comment]
This looks great, I like @yurm04 suggestion! Nice revision 👍 

> it wouldn't be inconsistent with other ways we use non-class selectors in this file but I'm not sure if the file you're referring to is the PatternsPage one

Sorry for the confusion... I sill read the indentations and thought [this was](https://github.com/Shopify/polaris/pull/10469/commits/e9abfd13e8e859688e515ec56af9a82618f8bb69#diff-d695ba67d0255cdbfa3f5593eb12860c86c98419c290c0dc915fa14ae3c0c61bL207) targeting all `dl`'s though now I see it is scoped under a class selector 😅 now realizing that wouldn't even matter since it was in a `.module.scss` file. My apologies!

**Comment by laurkim** [comment]
> Sorry for the confusion... I sill read the indentations and thought [this was](https://github.com/Shopify/polaris/pull/10469/commits/e9abfd13e8e859688e515ec56af9a82618f8bb69#diff-d695ba67d0255cdbfa3f5593eb12860c86c98419c290c0dc915fa14ae3c0c61bL207) targeting all `dl`'s though now I see it is scoped under a class selector 😅 now realizing that wouldn't even matter since it was in a `.module.scss` file. My apologies!

No worries at all! Just wanted to make sure I understood which file you were referencing and double check that I wasn't inadvertently breaking convention without realizing 🤝

**Pull request merged**
