### PR TITLE
[TextField] Fix input focus loss on vertical content change

### PR DESCRIPTION
**Pull request by laurkim**
### WHY are these changes introduced?

Fixes [#63582](https://github.com/Shopify/web/issues/63582).

When vertical content is added to the `Combobox`, the `TextField` remains focused but the input inside loses focus. This was causing issues in Admin where you would click outside of the focused TextField to close the popover pane but it would remain open.

### WHAT is this pull request doing?

Adds `verticalContent` to the hook that determines whether or not to focus the TextField input so that it's also triggered when appliedTags change.

[Spin](https://shop1.shopify.tag-sugges.lo-kim.us.spin.dev/admin/products/2)
I created a snapshot of these changes and included it in my spinstance for testing in Admin.
    <details>
      <summary>Before — input loses focus when adding applied tag</summary>
      Before — input loses focus when adding applied tag
    </details>
    <details>
      <summary>After — input stays in focus when adding applied tag</summary>
      After — input stays in focus when adding applied tag
    </details>

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useState, useCallback, useMemo} from 'react';

import {
  Page,
  Combobox,
  TextStyle,
  Stack,
  Tag,
  Listbox,
  EmptySearchResult,
} from '../src';

export function Playground() {
  const [selectedTags, setSelectedTags] = useState([]);
  const [value, setValue] = useState('');
  const [suggestion, setSuggestion] = useState('');
  const [focused, setFocused] = useState(false);

  const handleActiveOptionChange = useCallback(
    (activeOption) => {
      const activeOptionIsAction = activeOption === value;

      if (!activeOptionIsAction && !selectedTags.includes(activeOption)) {
        setSuggestion(activeOption);
      } else {
        setSuggestion('');
      }
    },
    [value, selectedTags],
  );

  const updateSelection = useCallback(
    (selected) => {
      const nextSelectedTags = new Set([...selectedTags]);

      if (nextSelectedTags.has(selected)) {
        nextSelectedTags.delete(selected);
      } else {
        nextSelectedTags.add(selected);
      }
      setSelectedTags([...nextSelectedTags]);
      setValue('');
      setSuggestion('');
    },
    [selectedTags],
  );

  const removeTag = useCallback(
    (tag) => () => {
      updateSelection(tag);
    },
    [updateSelection],
  );

  const getAllTags = useCallback(() => {
    const savedTags = ['Rustic', 'Antique', 'Vinyl', 'Vintage', 'Refurbished'];
    return [...new Set([...savedTags, ...selectedTags].sort())];
  }, [selectedTags]);

  const formatOptionText = useCallback(
    (option) => {
      const trimValue = value.trim().toLocaleLowerCase();
      const matchIndex = option.toLocaleLowerCase().indexOf(trimValue);

      if (!value || matchIndex === -1) return option;

      const start = option.slice(0, matchIndex);
      const highlight = option.slice(matchIndex, matchIndex + trimValue.length);
      const end = option.slice(matchIndex + trimValue.length, option.length);

      return (
        <p>
          {start}
          <TextStyle variation="strong">{highlight}</TextStyle>
          {end}
        </p>
      );
    },
    [value],
  );

  const options = useMemo(() => {
    let list;
    const allTags = getAllTags();
    const filterRegex = new RegExp(value, 'i');

    if (value) {
      list = allTags.filter((tag) => tag.match(filterRegex));
    } else {
      list = allTags;
    }

    return [...list];
  }, [value, getAllTags]);

  const verticalContentMarkup =
    selectedTags.length > 0 ? (
      <Stack spacing="extraTight" alignment="center">
        {selectedTags.map((tag) => (
          <Tag key={`option-${tag}`} onRemove={removeTag(tag)}>
            {tag}
          </Tag>
        ))}
      </Stack>
    ) : null;

  const optionMarkup =
    options.length > 0
      ? options.map((option) => {
          return (
            <Listbox.Option
              key={option}
              value={option}
              selected={selectedTags.includes(option)}
              accessibilityLabel={option}
            >
              <Listbox.TextOption selected={selectedTags.includes(option)}>
                {formatOptionText(option)}
              </Listbox.TextOption>
            </Listbox.Option>
          );
        })
      : null;

  const noResults = value && !getAllTags().includes(value);

  const actionMarkup = noResults ? (
    <Listbox.Action value={value}>{`Add "${value}"`}</Listbox.Action>
  ) : null;

  const emptyStateMarkup = optionMarkup ? null : (
    <EmptySearchResult
      title=""
      description={`No tags found matching "${value}"`}
    />
  );

  const listboxMarkup =
    optionMarkup || actionMarkup || emptyStateMarkup ? (
      <Listbox
        autoSelection="FIRST"
        onSelect={updateSelection}
        onActiveOptionChange={handleActiveOptionChange}
      >
        {actionMarkup}
        {optionMarkup}
      </Listbox>
    ) : null;

  const handleFocus = useCallback(() => {
    setFocused(true);
  }, [focused]);

  const handleBlur = useCallback(() => {
    setSuggestion('');
    setFocused(false);
  }, [value]);

  return (
    <Page>
      <div style={{height: '250px'}}>
        <Combobox
          allowMultiple
          activator={
            <Combobox.TextField
              autoComplete="off"
              label="Tags"
              value={value}
              placeholder="Search tags"
              suggestion={suggestion}
              verticalContent={verticalContentMarkup}
              focused={focused}
              onChange={setValue}
              onFocus={handleFocus}
              onBlur={handleBlur}
            />
          }
        >
          {listboxMarkup}
        </Combobox>
      </div>
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by chloerice — APPROVED** [review]
Noice 💯

**Review by sarahill — APPROVED** [review]
🔥 ❇️

**Pull request merged**
