### PR TITLE
Migrate `space` custom properties from v11 to v12

### LINKED ISSUE #10535: Run `space` migration in polaris
>[!WARNING]
> Do not merge the PR for this until the PR for #10536 is ready. (Checked using [the following code search](https://github.com/search?type=code&q=repo%3Ashopify%2Fpolaris+OR+repo%3Ashopify%2Fweb+OR+repo%3Ashopify%2Fapp-bridge+OR+repo%3Ashopify%2Fapp-kit+OR+repo%3Ashopify%2Fflow-app+OR+repo%3Ashopify%2Fmagic-ui+OR+repo%3Ashopify%2Fonline-store-ui+OR+repo%3Ashopify%2Fonline-store-web+OR+repo%3Ashopify%2Femail+%2F--p-space-%5B%5Cw-%5D%2B%3F%3A%2F))

## Migration

📝 [Example PR format](https://github.com/Shopify/web/pull/90842)

To replace these deprecated `space` custom properties, you can run the snapshot of the [`v12-styles-replace-custom-property-space`](https://github.com/Shopify/polaris/pull/10305) migration. Please reference the recommended token migration workflow section below for additional migration support.

```
cd polaris-react
```

```
npx @shopify/polaris-migrator@0.0.0-snapshot-release-20230918165951 \
  v12-styles-replace-custom-property-space \
  'src/**/*.scss'
```

>[!NOTE]
> If you get an error saying the migration doesn’t exist with a snapshot or you don’t see up to date migration changes, then delete `node-modules` folder in polaris at the top level. After the migration if you need to run `yarn` commands remember to `yarn` at polaris level.

## Recommended token migration workflow

When running token migrations we suggest the following workflow:

- Handle automated migrations
  ```sh
  # Example migration
  npx @shopify/polaris-migrator ...
  # Stage all migrated files
  git add .
  # Format staged files only
  git diff --staged --name-only | xargs npx prettier --write
  # Commit automated migrations
  git commit -m "Migrate space custom properties from Polaris v11 to v12"
  ```
- Handle manual migrations
  - Search for token RegExps and handle manual migrations (see Post-migration section below)
    <br>

  ```sh
  # Stage all manually migrated files
  git add .
  # Format staged files only
  git diff --staged --name-only | xargs npx prettier --write
  # Commit manual migrations
  git commit -m "Manually migrate space custom properties from Polaris v11 to v12"
  ```

- Check for errors after all custom property migrations are finished

  ```sh
  # Change to polaris root directory 
  cd ..
  # Install dependencies
  yarn 
  # Run stylelint against polaris-react
  npx stylelint 'polaris-react/src/**/*.scss'
  ```

## Post-migration validation

After migrating use the following RegExp to check for any additional instances of `space` custom properties across all file types:

<details>
  <summary>Check RegExp for hardcoded <code>space</code> custom properties across all file types</summary>

```
(?:--p-space-05|--p-space-1|--p-space-1_5-experimental|--p-space-2|--p-space-3|--p-space-4|--p-space-5|--p-space-6|--p-space-8|--p-space-10|--p-space-12|--p-space-16|--p-space-20|--p-space-24|--p-space-28|--p-space-32)(?![\w-])
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Tooltip padding="..." /&gt;</code> props</summary>

```
<Tooltip[^>\w](?:[^>]|\n)*?padding
```
> [!Note]
> Please make sure to update `export type Padding = 'default' | Extract<SpaceScale, '4'>;` inside Tooltip.
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;HorizontalGrid gap="..." /&gt;</code> props</summary>

```
<HorizontalGrid[^>\w](?:[^>]|\n)*?gap
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box padding="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?padding
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box paddingBlockStart="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?paddingBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box paddingBlockEnd="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?paddingBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box paddingInlineStart="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?paddingInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box paddingInlineEnd="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?paddingInlineEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box insetBlockStart="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?insetBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box insetBlockEnd="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?insetBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box insetInlineStart="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?insetInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box insetInlineEnd="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?insetInlineEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;VerticalStack gap="..." /&gt;</code> props</summary>

```
<VerticalStack[^>\w](?:[^>]|\n)*?gap
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;HorizontalStack gap="..." /&gt;</code> props</summary>

```
<HorizontalStack[^>\w](?:[^>]|\n)*?gap
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Choice bleed="..." /&gt;</code> props</summary>

```
<Choice[^>\w](?:[^>]|\n)*?bleed
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Choice bleedBlockStart="..." /&gt;</code> props</summary>

```
<Choice[^>\w](?:[^>]|\n)*?bleedBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Choice bleedBlockEnd="..." /&gt;</code> props</summary>

```
<Choice[^>\w](?:[^>]|\n)*?bleedBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Choice bleedInlineStart="..." /&gt;</code> props</summary>

```
<Choice[^>\w](?:[^>]|\n)*?bleedInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Choice bleedInlineEnd="..." /&gt;</code> props</summary>

```
<Choice[^>\w](?:[^>]|\n)*?bleedInlineEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;RadioButton bleed="..." /&gt;</code> props</summary>

```
<RadioButton[^>\w](?:[^>]|\n)*?bleed
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;RadioButton bleedBlockStart="..." /&gt;</code> props</summary>

```
<RadioButton[^>\w](?:[^>]|\n)*?bleedBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;RadioButton bleedBlockEnd="..." /&gt;</code> props</summary>

```
<RadioButton[^>\w](?:[^>]|\n)*?bleedBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;RadioButton bleedInlineStart="..." /&gt;</code> props</summary>

```
<RadioButton[^>\w](?:[^>]|\n)*?bleedInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;RadioButton bleedInlineEnd="..." /&gt;</code> props</summary>

```
<RadioButton[^>\w](?:[^>]|\n)*?bleedInlineEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Checkbox bleed="..." /&gt;</code> props</summary>

```
<Checkbox[^>\w](?:[^>]|\n)*?bleed
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Checkbox bleedBlockStart="..." /&gt;</code> props</summary>

```
<Checkbox[^>\w](?:[^>]|\n)*?bleedBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Checkbox bleedBlockEnd="..." /&gt;</code> props</summary>

```
<Checkbox[^>\w](?:[^>]|\n)*?bleedBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Checkbox bleedInlineStart="..." /&gt;</code> props</summary>

```
<Checkbox[^>\w](?:[^>]|\n)*?bleedInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Checkbox bleedInlineEnd="..." /&gt;</code> props</summary>

```
<Checkbox[^>\w](?:[^>]|\n)*?bleedInlineEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Stack gap="..." /&gt;</code> props</summary>

```
<Stack[^>\w](?:[^>]|\n)*?gap
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Grid gap="..." /&gt;</code> props</summary>

```
<Grid[^>\w](?:[^>]|\n)*?gap
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Grid gapX="..." /&gt;</code> props</summary>

```
<Grid[^>\w](?:[^>]|\n)*?gapX
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Grid gapY="..." /&gt;</code> props</summary>

```
<Grid[^>\w](?:[^>]|\n)*?gapY
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Card padding="..." /&gt;</code> props</summary>

```
<Card[^>\w](?:[^>]|\n)*?padding
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginInline="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginInline
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginBlock="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginBlock
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginBlockStart="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginBlockEnd="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginInlineStart="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginInlineEnd="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginInlineEnd
```
</details>

#### Replacement maps

| Deprecated CSS Custom Property   | Replacement Value |
| ---------------- | ----------------- |
| `--p-space-05` | `--p-space-050` | 
| `--p-space-1` | `--p-space-100` | 
| `--p-space-1_5-experimental` | `--p-space-150` | 
| `--p-space-2` | `--p-space-200` | 
| `--p-space-3` | `--p-space-300` |
| `--p-space-4` | `--p-space-400` | 
| `--p-space-5` | `--p-space-500` | 
| `--p-space-6` | `--p-space-600` | 
| `--p-space-8` | `--p-space-800` | 
| `--p-space-10` | `--p-space-1000` | 
| `--p-space-12` | `--p-space-1200` | 
| `--p-space-16` | `--p-space-1600` | 
| `--p-space-20` | `--p-space-2000` | 
| `--p-space-24` | `--p-space-2400` | 
| `--p-space-28` | `--p-space-2800` | 
| `--p-space-32` | `--p-space-3200` |

### PR DESCRIPTION
**Pull request by laurkim**
### WHY are these changes introduced?

Resolves #10535.
Migrates `space` custom properties from `v11` to `v12`. 
This PR includes both automated and manual migrations.

### WHAT is this pull request doing?

To migrate `space` custom properties, the flow was to: 
- Handle automatic migrations
    ```sh
    # Space migration
    npx @shopify/polaris-migrator@0.0.0-snapshot-release-20230918165951 \
    v12-styles-replace-custom-property-space \
    'src/**/*.scss'
    # Stash files with "polaris-migrator:" comments
    git stash push $(grep -r -l "polaris-migrator:" $(git ls-files -m))
    # Stage all migrated files
    git add .
    # Format staged files only
    git diff --staged --name-only | xargs npx prettier --write
    # Commit automated migrations
    git commit -m "Migrate space custom properties from v11 to v12" 
    ```
- Handle manual migrations
    ```sh
    # Bring back the files with "polaris-migrator:" comments
    git stash pop
    ```
    - Search for "polaris-migrator:" comments and handle manual migrations
    - Search for and handle manual migrations (e.g. <Box padding="1_5_experimental">)
    <br>

    ```sh
    # Stage all manually migrated files 
    git add .
    # Format staged files only
    git diff --staged --name-only | xargs npx prettier --write 
    #  Commit manual migrations
    git commit -m "Manually migrate space custom properties from v11 to v12"

    ```
- Check for errors after all custom property migrations are finished
    ```sh
    # Run stylelint against polaris-react
    npx stylelint 'polaris-react/src/**/*.scss'
    ```

#### Post-migration validation

After migrating use the following RegExp to check for any additional instances of `space` custom properties across all file types:

<details>
  <summary>Check RegExp for hardcoded <code>space</code> custom properties across all file types</summary>

```
(?:--p-space-05|--p-space-1|--p-space-1_5-experimental|--p-space-2|--p-space-3|--p-space-4|--p-space-5|--p-space-6|--p-space-8|--p-space-10|--p-space-12|--p-space-16|--p-space-20|--p-space-24|--p-space-28|--p-space-32)(?![\w-])
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Tooltip padding="..." /&gt;</code> props</summary>

```
<Tooltip[^>\w](?:[^>]|\n)*?padding
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;HorizontalGrid gap="..." /&gt;</code> props</summary>

```
<HorizontalGrid[^>\w](?:[^>]|\n)*?gap
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box padding="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?padding
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box paddingBlockStart="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?paddingBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box paddingBlockEnd="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?paddingBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box paddingInlineStart="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?paddingInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box paddingInlineEnd="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?paddingInlineEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box insetBlockStart="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?insetBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box insetBlockEnd="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?insetBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box insetInlineStart="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?insetInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Box insetInlineEnd="..." /&gt;</code> props</summary>

```
<Box[^>\w](?:[^>]|\n)*?insetInlineEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;VerticalStack gap="..." /&gt;</code> props</summary>

```
<VerticalStack[^>\w](?:[^>]|\n)*?gap
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;HorizontalStack gap="..." /&gt;</code> props</summary>

```
<HorizontalStack[^>\w](?:[^>]|\n)*?gap
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Choice bleed="..." /&gt;</code> props</summary>

```
<Choice[^>\w](?:[^>]|\n)*?bleed
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Choice bleedBlockStart="..." /&gt;</code> props</summary>

```
<Choice[^>\w](?:[^>]|\n)*?bleedBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Choice bleedBlockEnd="..." /&gt;</code> props</summary>

```
<Choice[^>\w](?:[^>]|\n)*?bleedBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Choice bleedInlineStart="..." /&gt;</code> props</summary>

```
<Choice[^>\w](?:[^>]|\n)*?bleedInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Choice bleedInlineEnd="..." /&gt;</code> props</summary>

```
<Choice[^>\w](?:[^>]|\n)*?bleedInlineEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;RadioButton bleed="..." /&gt;</code> props</summary>

```
<RadioButton[^>\w](?:[^>]|\n)*?bleed
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;RadioButton bleedBlockStart="..." /&gt;</code> props</summary>

```
<RadioButton[^>\w](?:[^>]|\n)*?bleedBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;RadioButton bleedBlockEnd="..." /&gt;</code> props</summary>

```
<RadioButton[^>\w](?:[^>]|\n)*?bleedBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;RadioButton bleedInlineStart="..." /&gt;</code> props</summary>

```
<RadioButton[^>\w](?:[^>]|\n)*?bleedInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;RadioButton bleedInlineEnd="..." /&gt;</code> props</summary>

```
<RadioButton[^>\w](?:[^>]|\n)*?bleedInlineEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Checkbox bleed="..." /&gt;</code> props</summary>

```
<Checkbox[^>\w](?:[^>]|\n)*?bleed
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Checkbox bleedBlockStart="..." /&gt;</code> props</summary>

```
<Checkbox[^>\w](?:[^>]|\n)*?bleedBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Checkbox bleedBlockEnd="..." /&gt;</code> props</summary>

```
<Checkbox[^>\w](?:[^>]|\n)*?bleedBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Checkbox bleedInlineStart="..." /&gt;</code> props</summary>

```
<Checkbox[^>\w](?:[^>]|\n)*?bleedInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Checkbox bleedInlineEnd="..." /&gt;</code> props</summary>

```
<Checkbox[^>\w](?:[^>]|\n)*?bleedInlineEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Stack gap="..." /&gt;</code> props</summary>

```
<Stack[^>\w](?:[^>]|\n)*?gap
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Grid gap="..." /&gt;</code> props</summary>

```
<Grid[^>\w](?:[^>]|\n)*?gap
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Grid gapX="..." /&gt;</code> props</summary>

```
<Grid[^>\w](?:[^>]|\n)*?gapX
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Grid gapY="..." /&gt;</code> props</summary>

```
<Grid[^>\w](?:[^>]|\n)*?gapY
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Card padding="..." /&gt;</code> props</summary>

```
<Card[^>\w](?:[^>]|\n)*?padding
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginInline="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginInline
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginBlock="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginBlock
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginBlockStart="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginBlockStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginBlockEnd="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginBlockEnd
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginInlineStart="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginInlineStart
```
</details>

<details>
  <summary>Check RegExp for outdated <code>&lt;Bleed marginInlineEnd="..." /&gt;</code> props</summary>

```
<Bleed[^>\w](?:[^>]|\n)*?marginInlineEnd
```
</details>

#### Replacement maps

| Deprecated CSS Custom Property   | Replacement Value |
| ---------------- | ----------------- |
| `--p-space-05` | `--p-space-050` | 
| `--p-space-1` | `--p-space-100` | 
| `--p-space-1_5-experimental` | `--p-space-150` | 
| `--p-space-2` | `--p-space-200` | 
| `--p-space-3` | `--p-space-300` |
| `--p-space-4` | `--p-space-400` | 
| `--p-space-5` | `--p-space-500` | 
| `--p-space-6` | `--p-space-600` | 
| `--p-space-8` | `--p-space-800` | 
| `--p-space-10` | `--p-space-1000` | 
| `--p-space-12` | `--p-space-1200` | 
| `--p-space-16` | `--p-space-1600` | 
| `--p-space-20` | `--p-space-2000` | 
| `--p-space-24` | `--p-space-2400` | 
| `--p-space-28` | `--p-space-2800` | 
| `--p-space-32` | `--p-space-3200` | 

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by lgriffee — APPROVED** [review]
Checked over the all the manual migrations and they LGTM! 💯🚢✨🎉 Also quickly checked over the automatic ones and they also look good.

**Review by heyjoethomas — COMMENTED** [review]
🚀

**Review by heyjoethomas — APPROVED** [review]

**Review by sarahill — APPROVED** [review]
🎉

**Pull request merged**
