### PR TITLE
[Banner] Fix Banner secondaryAction content wrapping in Firefox

### LINKED ISSUE #620: Banner Component - secondaryAction content wrapping in FireFox
# Issue summary

In FireFox v63 the Banner component `secondaryAction` prop `content` string is wrapping the last word to a new line when there is clearly enough room for the word on the same line. This does not occur in Chrome.

## Expected behavior

We expect that the content in the `secondaryAction`  prop to all remain on the same line until the screen is too narrow to accommodate this, in which case (i.e. a mobile 340px screen) it should wrap.

## Actual behavior

When provided the following text: "Learn more about marketplace requirements" the word "requirements" wraps to a new line on full width desktop screen in FireFox.

[here's the issue on codeSandbox](https://codesandbox.io/s/kx72lzl23o)

## Steps to reproduce the problem

1. use a `<Banner>` component
2. provide a `secondaryAction` prop with a content prop and a url prop
3. open in FireFox and observe the last word wrapping on desktop

[view the issue on codeSandbox](https://codesandbox.io/s/kx72lzl23o)

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

[Here's the issue on codeSandbox](https://codesandbox.io/s/kx72lzl23o)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: `^2.7.2`
- Browser: FireFox
- Device: Macbook Pro
- Operating System: Mac OS High Sierra v10.13.6

### PR DESCRIPTION
**Pull request by juwanpetty**
Fixes #620 

### WHY are these changes introduced?
Fixes Banner secondaryAction content wrapping in Firefox  when there is enough room for the word on the same line. 

#### Before
image

#### After 
image

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)

### CODE REVIEW

**Comment by AndrewMusgrave** [comment]
👋 When your pr is ready for review feel free to add `polaris-reviews` 😄

**Comment by juwanpetty** [comment]
Hey @AndrewMusgrave I'm getting this style lint error in my markdown file.
Really confused on why it would be checking for that in this file type

image

**Comment by danrosenthal** [comment]
> Hey @AndrewMusgrave I'm getting this style lint error in my markdown file.
Really confused on why it would be checking for that in this file type

In this case removing the empty line 10 on your UNRELEASED.md ought to fix it. If not, you can do as the failed test suggests and run `yarn run sewing-kit format` to auto format.

**Comment by BPScott** [comment]
Setting `white-space: nowrap;` Will mean that long text in the secondary action won't wrap at all, which is a particular problem on small screens as it means it'll scroll off the edge and render it unreadable.

screen shot 2018-12-10 at 1 54 35 pm

**Comment by danrosenthal** [comment]
Thanks for this fix @juwanpetty! I went ahead and pushed a change adding an example to the README so we can catch problems like this if they re-emerge.

When 🎩ing, I noticed that the secondary action does not align nicely with the primary action when it drops down to a second line. Could you work on that alignment a bit?

|small screen alignment|
|-|
|screen shot 2018-12-14 at 11 15 28 am|

**Comment by juwanpetty** [comment]
Yeah sure thing @danrosenthal

**Comment by dpersing** [comment]
Thanks for making that style tweak, @juwanpetty! It looks like we just need an update to `UNRELEASED.md`.

**Comment by juwanpetty** [comment]
@dpersing no problem, made those changes 👍

**Pull request merged**
