### PR TITLE
[ResourceList] Fix for the plural resource name when totalItemsCount is greater than 1

### LINKED ISSUE #2299: [ResourceList] totalItemsCount causes singular of resource to be used when showing one resource
## Issue summary

When using the `totalItemsCount` and you have only 1 item showing of more than 1 item, the text appears to use the singular form of the resource name.

## Expected behavior

When the `totalItemsCount` is being used, the proper plurality should be shown regardless of the number of items shown. This will vary by language plurality rules, but for English it should show the plural unless `totalItemsCount` is 1.

## Actual behavior

For example, if you have 50 customers and only show 1 customer, it'll say "Showing 1 of 50 customer". You can come across this when you are paginating resources and only have 1 item left on the page. If you have 21 customers and page every 10 customers, the third page will say "Showing 1 of 21 customer".

## Steps to reproduce the problem

1. Create a ResourceList.
1. Set the `totalItemsCount` to a value greater than 1.
1. Set the `items` to only display 1 resource item.

## Reduced test case

The following [CodeSandbox](https://codesandbox.io/s/shopify-polaris-react-typescript-playground-w6ige) shows off the behavior:

image

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.6.0
- Browser: Google Chrome 77.0.3865.120
- Device: MacBook Pro
- Operating System: macOS Catalina 10.15

### PR DESCRIPTION
**Pull request by mbaumbach**
### WHY are these changes introduced?

Fixes #2299 

When the `ResourceList` has only item showing, but a `totalItemsCount` greater than 1, it was using the singular form of the resource name when it should use the plural.

### WHAT is this pull request doing?

Whenever there's a `totalItemsCount` and it's not equal to 1, it will use the plural form of the resource name.

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the [Polaris UI kit](https://polaris.shopify.com/resources/polaris-ui-kit)

### CODE REVIEW

**Comment by BPScott** [comment]
Are the changes to  eslintignore and all the components other than ResourceList desired? They all look unrelated?

**Comment by mbaumbach** [comment]
@BPScott Nope, not desired. I think that may have been due to a merge with master. I thought I rebased those when trying to resolve the conflicts with `UNRELEASED.md` though.

I can always create a new branch with just these changes if that's preferred.

**Comment by BPScott** [comment]
Rebasing this atop latest master is fine, no need for new branches and new PRs :)

**Comment by mbaumbach** [comment]
Apologies about that auto-close of the PR. Should be all set now, I think.

**Comment by tmlayton** [comment]
Will squash and merge once the checks pass

**Pull request merged**
