### PR TITLE
[Form] Add tabIndex={-1} to implicit submit form

### PR DESCRIPTION
**Pull request by dleroux**
### WHY are these changes introduced?

While doing an a11y audit on our Form component I found that our Form component is failing because `ARIA hidden element must not contain focusable elements`.

Our Form contains an implicitSubmit prop which generates a visually hidden submit button with aria-hidden set to true.

### WHAT is this pull request doing?

adds a tabIndex={-1} to our Form implied submit button. 

## 

### How to 🎩

Using Fast pass on the [Accessibility extension for web](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en) ensure there are no errors with the playground below.

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useState, useCallback} from 'react';
import {Page, Form, FormLayout, TextField, Button} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      <FormExample />
    </Page>
  );
}

class FormExample extends React.Component {
  state = {
    url: '',
  };

  render() {
    const {url} = this.state;

    return (
      <Form noValidate onSubmit={this.handleSubmit}>
        <FormLayout>
          <TextField
            value={url}
            onChange={this.handleChange('url')}
            label="App URL"
            type="url"
          />

          <Button submit>Submit</Button>
        </FormLayout>
      </Form>
    );
  }

  handleSubmit = (event) => {
    this.setState({url: ''});
  };

  handleChange = (field) => {
    return (value) => this.setState({[field]: value});
  };
}
```

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the [Polaris UI kit](https://polaris.shopify.com/resources/polaris-ui-kit)

### CODE REVIEW

**Comment by dleroux** [comment]
@dpersing once you confirm that this in fact the behavior we want I'll update the changelog.

**Comment by dleroux** [comment]
I believe is so that the form does submit by simply clicking enter as oppose to actually clicking on the button. Display none wouldn't have the same effect because the button would not be in the DOM.

If this is a temporary fix, what would the right fix be?

**Comment by kaelig** [comment]
Would it help consumers to see an example in the style guide, or is this an edge case we want to discourage?

**Comment by dleroux** [comment]
> Would it help consumers to see an example in the style guide, or is this an edge case we want to discourage?

I'm not sure it's worth it because it is the default behavior. I'm guessing a safeguard for when people add more than 1 field and no submit button is present, clicking enter would not trigger the on submit.

**Pull request merged**
