### PR TITLE
[Tabs] Adds a means to hide tabs if there is only one

### PR DESCRIPTION
**Pull request by jared-dykstra**
Devs had a need to create a HOC `Tabs` component for cases when the number of tabs was dynamic and the desire was to hide the tab UI if there is only one tab.

For example: https://github.com/Shopify/web/pull/22045/files#diff-c2ee73134750ecc64faa9c16571e09cf

### WHAT is this pull request doing?

This PR adds a new optional prop to `Tabs`.  If undefined or `false`, current behavior is retained.  If `true` and if there is not more than one visible tab, `children` is rendered directly, without being wrapped with the tabs markup.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page, Card, Tabs} from '../src';

export function Playground() {
  const [selected, setSelected] = React.useState(0);

  const handleTabChange = React.useCallback(
    (selectedTabIndex) => setSelected(selectedTabIndex),
    [],
  );

  const tabs = [
    {
      id: 'prospects',
      content: 'Prospects',
      panelID: 'prospects-content',
    },
    // {
    //   id: 'second',
    //   content: 'Second',
    //   panelID: 'second-content',
    // },
  ];

  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}

      <Card>
        <Tabs
          tabs={tabs}
          selected={selected}
          onSelect={handleTabChange}
          optionalSingleTab
        >
          <Card.Section title={tabs[selected].content}>
            <p>Tab {selected} selected</p>
          </Card.Section>
        </Tabs>
      </Card>
    </Page>
  );
}
```

</details>

### 🎩 checklist

* [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Comment by jared-dykstra** [comment]
@briangilhutton - This comes out of a PR you were recently working on:  https://github.com/Shopify/web/pull/22045

**Comment by dleroux** [comment]
Thanks @jared-dykstra. Although I'm not sure there's value in adding this prop at this time. It adds code for a use case that is seldom needed and probably more explicit if conditionally rendered in the parent. Have you found a need for multiple uses of this?

**Comment by jared-dykstra** [comment]
@dleroux - I don't have enough context to know if there are multiple needs for something like this, unfortunately. 

@qq99 - are you able to provide this additional context?

**Comment by qq99** [comment]
From a quick code search, I found 2 more examples of this kind of thing @ `ImagePickerModal` and `FraudModal` in admin, so that'd be 3 spots that could use this prop

**Comment by dleroux** [comment]
Interesting. I feel like this shouldn't be a concern for tabs, tabs that don't render tabs. That might just be me though.

**Comment by AndrewMusgrave** [comment]
I agree with Dan, I'm not sure this needs to be a concern of `Tabs`. It seems odd to me for `Tabs` to not render `Tabs`. Duplicating the logic where it's needed doesn't seem bad to me as it's rather small

```tsx
const tabsMarkup = tabs.length ? <Tabs {...tabsProps}> : children;
```

**Comment by jared-dykstra** [comment]
@AndrewMusgrave - Minor correction: `tabs.length > 1`  (not falsey)

It doesn't seem like there is much appetite for this PR.  If not, that's OK.  I wanted to propose it anyway with the hopes of eventually removing (OptionalTabs.tsx)[ https://github.com/Shopify/web/pull/22045/files#diff-c2ee73134750ecc64faa9c16571e09cf] that was introduced in the referenced PR.

**Comment by tmlayton** [comment]
Thanks for proposing this. I have the same opinion that this shouldn’t be a tab concern.

**Comment by dleroux** [comment]
Sounds like we're going to hold off on this, I'll close the PR for now. If this comes up more often feel free to bring it up again.

**Pull request closed without merging**
