### PR TITLE
[CalloutCard] Add dismiss button & callback

### LINKED ISSUE #353: No built-in way to dismiss callout cards
The "best practices" documentation for the `CalloutCard` component state that cards "should be dismissable so merchants can get rid of cards about features they’re not interested in". However, unlike other components (e.g. `Banner`), there doesn't seem to be any built-in way to dismiss the callout card. What's the recommended way of doing this?

### PR DESCRIPTION
**Pull request by andrewlo**
### WHY are these changes introduced?

Resolves #353 

In the app I'm working on we use a `CalloutCard` with dismiss button like banners have. I noticed this functionality is missing from the component & that there's an issue requesting this.

### WHAT is this pull request doing?

Add a prop `onDismiss` which when present, adds the dismiss button with the same functionality & style as the `Banner` component.

Before:
screen shot 2018-12-04 at 2 10 51 pm

After (with onDismiss):
screen shot 2018-12-04 at 2 10 33 pm

From this issue: https://github.com/Shopify/polaris-react-deprecated/issues/1596 it seems like the same dismiss functionality as `Banner` is desired.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import * as React from 'react';
import {Page} from '@shopify/polaris';

interface State {}

export default class Playground extends React.Component<never, State> {
  render() {
    return (
      <Page title="Playground">
        <CalloutCard
          title="Customize the style of your checkout"
          illustration="https://cdn.shopify.com/s/assets/admin/checkout/settings-customizecart-705f57c725ac05be5a34ec20c05b94298cb8afd10aac7bd9c7ad02030f48cfa0.svg"
          primaryAction={{
            content: 'Customize checkout',
            url: 'https://www.shopify.com',
          }}
          onDismiss={() => console.log('dismiss')}
        >
          <p>Upload your store’s logo, change colors and fonts, and more.</p>
        </CalloutCard>
      </Page>
    );
  }
}
```

</details>

### 🎩 checklist

* [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [x] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)

### CODE REVIEW

**Comment by danrosenthal** [comment]
Also don't worry about the Percy failure. That is a flakey test to do with Popover rendering weirdness.

**Comment by danrosenthal** [comment]
@sarahill could you take a look at the alignment on this dismiss button? Does it feel like it should be closer to the corner to you?

**Comment by sarahill** [comment]
I agree with @danrosenthal we should move it up a bit to give it more separation from the illustration.

Curious if you've considered using the `secondaryAction` for Dismiss? The `x` feels a bit forced to me. I think it makes sense to have an option to dismiss but being so close to the illustration I find it gets lost.

screen shot 2018-12-12 at 3 19 42 pm

**Comment by andrewlo** [comment]
If secondary action works, feel free to close this PR unmerged. Based on the issues linked it seemed like there was a request to have an X like Banners have. Could be a good idea to show an example using secondaryAction with dismiss text to make it clear on the style guide as well

**Comment by danrosenthal** [comment]
Reopening this as @sarahill had some additional thoughts.

**Comment by sarahill** [comment]
Ok, I thought a little more about this. If we move the `x` up and position the illustration over it feels a little better.

@jessebc I would love to get your thoughts on this.

screen shot 2018-12-13 at 10 50 18 am

**Comment by jessebc** [comment]
Thoughts on the alignment? Is it the same that we use for banners?

**Comment by sarahill** [comment]
@jessebc It's up and over just a bit more than in banners but it's close. I think in this context it's better for visual alignment. Just seeing if you had any thoughts/concerns about the placement of the dismiss relative to the illustration.

**Comment by jessebc** [comment]
It seems to be working fine with that particular illustration!

(That being said... that illustration should either be updated or removed)

**Comment by sarahill** [comment]
@andrewlo let's go ahead with adding the `x`. just adjusting the placement.

Thanks for doing this and bearing with me!

**Comment by andrewlo** [comment]
Adjusted dismiss button position & shifted the illustration to the left when dismiss button exists.

This shows comparison for illustration position with & without dismiss:
screen shot 2018-12-17 at 10 32 05 am

**Comment by sarahill** [comment]
@andrewlo This looks good! Thanks for the changes 🎉

**Comment by danrosenthal** [comment]
Rebase, squash commits, and 🚢!

**Comment by andrewlo** [comment]
@danrosenthal @sarahill Thanks for the reviews!

**Pull request merged**
