### PR TITLE
Rename links for the updated IA on the styleguide

### PR DESCRIPTION
**Pull request by amrocha**
### WHY are these changes introduced?

https://github.com/Shopify/polaris-styleguide/pull/2314

### WHAT is this pull request doing?

Fixing links

## 

### How to 🎩

Build for the styleguide, then run the broken link checker

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
/* eslint-disable */

import * as React from 'react';
import {Page, AppProvider} from '@shopify/polaris';

interface State {}

export default class Playground extends React.Component<never, State> {
  render() {
    return (
      <AppProvider>
        <Page title="Playground">
          {/* Add the code you want to test here */}
        </Page>
      </AppProvider>
    );
  }
}
```

</details>

### 🎩 checklist

* [ ] Tested on mobile
* [ ] Tested on multiple browsers
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated [UNRELEASED.md](https://github.com/Shopify/polaris-react/blob/master/UNRELEASED.md)

### CODE REVIEW

**Comment by amrocha** [comment]
I know what that is, the config for CircleCI got messed up when we did the switch, I'll see if I can fix it

**Comment by tmlayton** [comment]
This just needed a rebase, also updated the changelog entry with the new PR link.

**Comment by danrosenthal** [comment]
What's the status on this PR @amrocha?

**Comment by amrocha** [comment]
Needs to be merged together with https://github.com/Shopify/polaris-styleguide/pull/2314 which isn't ready yet

**Pull request merged**
